### ISSUE TITLE
Mobilní zobrazení - zalamování názvu časopisu

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#119]
Ve verzi 3.0.1 se ještě objevil problém se zalamováním názvu časopisu v hlavičce webu. Při přístupu na web z mobilu, se někdy špatně zalamuje název, pokud je použité slovo "Časopis" nebo je vyplněný podtitul. Pokud je vyplněný jen titul, tak se to chová správně. 

@pkudela podíval by ses na to, prosím? Děkuju!

Je to celé trochu podivné, na počítači, ale ani pří přístupu z mobilu na testovací aplikaci na inovatika.dev se mi to nepovedlo nasimulovat. Na naší ostré verzi se to ale děje, například tady: https://asjournals.lib.cas.cz/ceskaliteratura/home

![image](https://user-images.githubusercontent.com/57805328/226361038-878e13d9-f49e-4d0d-8318-094badcc323c.png)
![image](https://user-images.githubusercontent.com/57805328/226361152-2247ed18-e07e-4485-9b16-a19b6c29e44e.png)

**Comment by pkudela** [comment]
Chovani v mobilnim zarizeni by jiz melo byt v poradku  viz. issue #133

**Comment by AnnaNajmanova** [comment]
Zalomení názvu časopisu ok, bylo by jenom potřeba posunout text na stránce pod obálku a tlačítka - viz. screenshot
![Mobilní zobrazení](https://github.com/ceskaexpedice/ASJournals/assets/89901869/2ae3c176-1591-49f4-98b0-acd7f1fa2bca)

**Comment by pkudela** [comment]
hotovo, jakmile nasadim na server, dam tomuto issue potrebny label, nyni je responsivni chovani takoveto (chovani menim pri breakpointu 599px):

<img width="790" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/9ccac4bc-2892-4112-8b3d-28dd5858bf4a">

<img width="508" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/69e389d3-92d6-4d4a-88f0-cf114d7838fa">

**Comment by pkudela** [comment]
nasazeno na serveru, prosim o otestovani

**Comment by pkudela** [comment]
hotovo

<img width="589" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/dd70ecf8-84e4-4e82-9775-8bfb5af3424b">

**Comment by kerschfilip** [comment]
je OK, díky
