### ISSUE TITLE
Redesign obrazovky prohlížečky

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#124]
V současnosti se po rozkliknutí článku zobrazuje čtečka PDF, jednotlivé informace o článku je potřeba si dále rozklikávat.

Navrhujeme rozdělit hlavní část obrazovky současné "prohlížečky" na dvě části: "detail" a "PDF". Která z nich se bude defaultně zobrazovat bude nastavitelné v administraci časopisu.

Na kartě "detail" budou vypsané všechny informace o článku. U autorů budou navíc role a identifikátory ROR a ORCID (budou-li dostupné). Navíc oproti původním informacím o článků by se měl zobrazovat i abstrakt (pokud ho článek má) a rovnou by se měla generovat citace.

Na kartě "PDF" by měla být prohlížečka. Navrhujeme integrovat stejnou, jaká je teď v klientovi ProArcu

Návrh nového uspořádání obrazovky: https://drive.google.com/drive/folders/1KDipR1rri419iXuf79IvgC94pL5w1mZW?usp=sharing

**Comment by kerschfilip** [comment]
Upravená obrazovka prohlížečky vypadá skvěle! Máme jen drobné připomínky :-)

- [ ] Prosím slova "detail" a "pdf" napsat s velkými písmeny, tedy "Detail" a "PDF"
- [ ] Označení metadat "datum publikování", "Autor" atd napsat prosím tučně, ne šedě jako je to teď 
<img width="1540" alt="Snímek obrazovky 2024-04-10 v 16 18 16" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/8e8a6c20-e219-4e96-9289-63453b58f246">

- [ ] Tlačítko pro zvětšení PDF na celou obrazovku nefunguje
<img width="240" alt="Snímek obrazovky 2024-04-10 v 16 20 02" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/86be66d5-edbf-4ed8-98a3-cc37c85ca50f">

- [ ] Dole mezi prohlížečkou a patičkou je bílý pruh, který se zdá zbytečný, šlo by ho odstranit?
<img width="1073" alt="Snímek obrazovky 2024-04-10 v 16 24 00" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/894e988c-bcad-46cf-b2cc-794a17058277">

---

A potom k bodu 
> Navrhujeme rozdělit hlavní část obrazovky současné "prohlížečky" na dvě části: "detail" a "PDF". Která z nich se bude defaultně zobrazovat bude nastavitelné v administraci časopisu.

V administraci jsem zatím nenašel možnost si vybrat, která z karet má být aktivovaná defaultně. Prosil bych o přidání téhle možnosti do karty Konfigurace v rámci administrace

Díky!

**Comment by pkudela** [comment]
> Upravená obrazovka prohlížečky vypadá skvěle! Máme jen drobné připomínky :-)
> 
> * [ ]  Prosím slova "detail" a "pdf" napsat s velkými písmeny, tedy "Detail" a "PDF"
> * [ ]  Označení metadat "datum publikování", "Autor" atd napsat prosím tučně, ne šedě jako je to teď
> **OK, udelam**
> <img alt="Snímek obrazovky 2024-04-10 v 16 18 16" width="1540" src="https://private-user-images.githubusercontent.com/57805328/321273404-8e8a6c20-e219-4e96-9289-63453b58f246.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjIzOTMsIm5iZiI6MTcxMjgyMjA5MywicGF0aCI6Ii81NzgwNTMyOC8zMjEyNzM0MDQtOGU4YTZjMjAtZTIxOS00ZTk2LTkyODktNjM0NTNiNThmMjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3NTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ODE1MDdkZjQ5MGU2OTY5ZjdlZjFkMTM0OGI3OTVhMmFmNjZiZTMyNjdkMGY4ZDMxMjBmZjVmNjAxNzUwMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0k8tqH-lJWgpT-mKMm351YohMYFQovKBFiFKXFPqxzU">
> * [ ]  Tlačítko pro zvětšení PDF na celou obrazovku nefunguje
> **tady jsme ho zamerne zakomentovali, ale uz si nepamatuju proc @albertoh vis proc?**
> <img alt="Snímek obrazovky 2024-04-10 v 16 20 02" width="240" src="https://private-user-images.githubusercontent.com/57805328/321273560-86be66d5-edbf-4ed8-98a3-cc37c85ca50f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjIzOTMsIm5iZiI6MTcxMjgyMjA5MywicGF0aCI6Ii81NzgwNTMyOC8zMjEyNzM1NjAtODZiZTY2ZDUtZWRiZi00ZWQ4LTk4YTMtY2MzN2M4NWNhNTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3NTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NDA5MzAzOTM1NmQ4YzhlNmFmNjFkNmYxNmJjMDE4ZmUxN2Y4YmUzNTYwOWI4NGE2MWM1Njk3MTQyMjljNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jns-v79CzShFDDaZiaxEm7u6D_5zdTKBGE1_asoJTIw">
> * [ ]  Dole mezi prohlížečkou a patičkou je bílý pruh, který se zdá zbytečný, šlo by ho odstranit?
> **je to ochrana zona obsahu, nemohu ji uplne odstranit, ale muzu zmensit na polovinu**
<img width="1511" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/b0739490-4da6-4db0-b2ed-ef2f785699ad">
> <img alt="Snímek obrazovky 2024-04-10 v 16 24 00" width="1073" src="https://private-user-images.githubusercontent.com/57805328/321275207-894e988c-bcad-46cf-b2cc-794a17058277.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjIzOTMsIm5iZiI6MTcxMjgyMjA5MywicGF0aCI6Ii81NzgwNTMyOC8zMjEyNzUyMDctODk0ZTk4OGMtYmNhZC00NmNmLWIyY2MtNzk0YTE3MDU4Mjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3NTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OWRiZDgwZmNhMjlmNGVhYmU5M2IyYmU0Y2JkYzEwNTYxNzk3ZmFlMjZkYmM0MGI1OTczZDJiNTg4MmY2YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VajdISW2nwdpsJYmAFrwlAalefDmENEmXpCQFj16MIY">
> A potom k bodu
> 
> > Navrhujeme rozdělit hlavní část obrazovky současné "prohlížečky" na dvě části: "detail" a "PDF". Která z nich se bude defaultně zobrazovat bude nastavitelné v administraci časopisu.
> 
> V administraci jsem zatím nenašel možnost si vybrat, která z karet má být aktivovaná defaultně. Prosil bych o přidání téhle možnosti do karty Konfigurace v rámci administrace
> 
<img width="1511" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/9d5e1777-a460-4a12-8d0a-76a898ecee86">
**OK, doplnime, pripravim a @albertoh dodela**
> Díky!

**Comment by kerschfilip** [comment]
> je to ochrana zona obsahu, nemohu ji uplne odstranit, ale muzu zmensit na polovinu viz. screenshot nize

Bezva, díky, takhle je to dobrý

**Comment by pkudela** [comment]
hotovo, nasazeno na serveru -> https://asjournals.inovatika.dev/, prosim o otestovani

**Comment by kerschfilip** [comment]
Všechny body jsou vyřešeném děkuju!

Při zobrazení na mobilu jsem si všiml, že záložka "ARTICLES" není přeložená do češtiny (ČLÁNKY). A že při překlikávání na detail a zpět na výběr článků se mi divně zvětšuje font: https://drive.google.com/file/d/1IZqOCSKyla584W6k0UwZUrtt97slfZ2f/view?usp=drive_link

**Comment by pkudela** [comment]
> Děkuju. Asi by bylo fajn to v tuhle chvíli projít a dopřeložit, co kde chybí. Dík :-)

ok, tohle issue teda prosim zavri a zaloz separatni issue na preklady a prirad to rovnou me, at se nam to nemicha
