### ISSUE TITLE
Možnost přidat k článkům seznam použité literatury

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#125]
V současnosti není možné zobrazovat u článku seznam použité literatury, protože není součástí metadat (a v dohledné době ani nebude).

Některé redakce by ale rády seznam literatury vyplňovaly, protože je to u zahraničních webů vědeckých časopisů standard a zvyšuje to pravděpodobnost nalezení článku. 

Navrhujeme, že na nově upraveném detailu článku se bude přihlášenému administrátorovi webu zobrazovat ikona tužky symbolizující, že může provádět úpravy. Po kliknutí na ikonu se mu otevře textové pole, kam může vyplnit soupis použité literatury v článku (povolen bude jen plain text). Nadpis textového pole bude volitelný. Bude-li textové pole prázdné, pak se nadpis pole zobrazovat nebude.

Návrh: https://drive.google.com/file/d/1Jhg25m2InWy2JkoJHoGTYHlq68OTXlJf/view?usp=sharing

návrh je závislý na realizaci redesignu detailu článku #124

**Comment by kerschfilip** [comment]
Změna: administrátor nebude vyplňovat seznam literatury sám přímo na webu, pouze se zde použitá literatura zobrazí - bude součástí MODSu článku - viz https://github.com/proarc/proarc-client/issues/435

Platí, že nadpis textového pole bude volitelný a bude-li textové pole prázdné, pak se nadpis pole zobrazovat nebude.

V nastavení webu časopisu by měla být možnost zobrazování literatury zapnout/vypnout

**Comment by albertoh** [comment]
@kerschfilip  Existuje nejaky zaznam, ktery seznam ma a kde to muzu testovat?

**Comment by kerschfilip** [comment]
@albertoh zatím ne, ještě není doladěná struktura v MODS, jak to správně zapisovat. Řeší se to tady: https://github.com/NLCR/Standard_NDK/issues/201

**Comment by kerschfilip** [comment]
Způsob zápisu seznamu použité literatury v MODS je popsaný tady: https://github.com/proarc/proarc-client/issues/435#issuecomment-2233067487

Na detailu článku v AS Journals by se seznam měl zobrazovat úplně dole (to znamená pod citací)

V případě, že je citace nestrukturovaná, zobrazit by se měl pouze text, který je obsahem `<relatedItem type="references" id="ref000x"><note type="source note">`. Každá relatedItem by se měla zobrazovat na samostatném řádku.

V případech, kdy by citace byly strukturované, bude potřeba složit jednotlivé součásti citace správně za sebe včetně interpunkce. Dodržet by se měla norma ISO 690. Pokusil jsem se připravit pseudomapovací schéma, pokud by nebylo pochopitelné, tak to zkusím ještě nějak jinak :-) 

```
{name/namePart[@family]}, {name/namePart[@given]}. {/titleInfo/title}. {originInfo/dateIssued}. {originInfo/place/placeTerm}:{originInfo/publisher}.
IF: {relatedItem[@type="host"]
    In: {relatedItem[@type="host"]/name/namePart[@family]}, {relatedItem[@type="host"]/name/namePart[@given]}. 
    {relatedItem[@type="host"]/titleInfo/title}

    IF {relatedItem[type="host"]/part
    , roč.{relatedItem[type="host"]/part/detail[@type="volume"]/number}, č. {relatedItem[type="host"]/part/detail[@type="issue"]/number}.
    }
    ELSE{
    . 
    }
     {relatedItem[@type="host"]/originInfo/dateIssued}. {relatedItem[@type="host"]/originInfo/place/placeTerm}:{relatedItem[@type="host"]/originInfo/publisher}. s. {part/extent/start}-{part/extent/end}
}
IF {identifier[@type="isbn"]}
    ISBN: {identifier[@type="isbn"]}.
}.
IF {identifier[@type="doi"]}
    DOI: https://doi.org/{identifier[@type="doi"]}.
}.
```

Příklady jsou uvedené zde: [structured_references.txt](https://github.com/user-attachments/files/16264449/structured_references.txt). V našem testovacím K7 jsou potom 2 příklady:

- nestrukturovaná citace: https://kramerius-test.lib.cas.cz/uuid/uuid:6ed2135a-8844-4235-b5ec-8da5f200601d a https://asjournals.inovatika.dev/ceskaliteraturaK7/article/uuid:6ed2135a-8844-4235-b5ec-8da5f200601d/detail
- strukturovaná citace: https://kramerius-test.lib.cas.cz/uuid/uuid:6ed2135a-8844-4235-b5ec-8da5f200601c a https://asjournals.inovatika.dev/ceskaliteraturaK7/article/uuid:6ed2135a-8844-4235-b5ec-8da5f200601c/detail

**Comment by albertoh** [comment]
Jsou data konziztentni?
Napriklad v uuid:6ed2135a-8844-4235-b5ec-8da5f200601c vidim:

`
<relatedItem id="ref0003" type="references">
      <titleInfo>
        <title>Populární romány Vlasty Javořické</title>
      </titleInfo>
      <name>
        <namePart type="family">Mocná</namePart>
        <namePart type="given">Dagmar</namePart>
      </name>
      <part>
        <extent unit="pages">
          <start>487</start>
          <end>509</end>
        </extent>
      </part>
      <relatedItem type="host">
        <titleInfo>
          <title>Česká literatura</title>
        </titleInfo>
        <originInfo>
          <dateIssued>1995</dateIssued>
        </originInfo>
        <part>
          <detail type="volume">
            <number>XLIII</number>
          </detail>
          <detail type="issue">
            <number>5</number>
          </detail>
        </part>
      </relatedItem>
    </relatedItem>
`

To znamena je 
relatedItem[@type="host"]
ale tam neni
relatedItem[@type="host"]/name/namePart[@family]}, {relatedItem[@type="host"]/name/namePart[@given]

**Comment by kerschfilip** [comment]
No, ono se ty jednotlivé reference budou dost lišit.

v relatedItem id="ref0003" je to citace článku z časopisu. Element `name` je tak jen u autorky článku. `relatedItem[@type="host"]`, tedy časopis, kde článek vyšel, autora nemá

naopak třeba v  relatedItem id="ref0002" je i `relatedItem[@type="host"]/name/...` Protože je to citace kapitoly, která má svou autorku a je zároveň součástí knihy, která má svého celkového editora. 

To znamená, že někdy v rámci relatedItem[@type="host"] může to jméno být a jindy ne. Oboje je přitom správně.

**Comment by albertoh** [comment]
Snad je tam vsechno

**Comment by kerschfilip** [comment]
U[ strukturované citace](https://asjournals.inovatika.dev/ceskaliteraturaK7/article/uuid:6ed2135a-8844-4235-b5ec-8da5f200601c/detail) se zobrazuje:

```
Doyle, Arthur Conan. 1982. Praha:: Mladá fronta. ISBN: 9788075851628.
Vlašín, Štěpán. Kniha o Čapkovi . 1988. Praha : Československý spisovatel
Mocná, Dagmar. Česká literatura , roč.XLIII, č. 5 1995.
Getta, Jelizaveta. Bohemica litteraria , roč.XXV, č. 1 2022. DOI: 10.5817/BL2022-1-5.
```

Správně to má být (tučně zvýrazněné změny):

Doyle, Arthur Conan. **Dobrodružství Sherlocka Holmese**. **Praha: Mladá fronta, 1982**. ISBN: 9788075851628.

- [ ] vypadl Název
- [ ] Praha: - jen jedna dvojtečka
- [ ] Přesunutí roku vydání za nakladatele (to jsem udělal blbě v tom schématu nahoře já)

**Kardyni-Pelikánová, Krystyna. Hra na detektivku.** **In:** Vlašín, Štěpán. Kniha o **Čapkovi.** Prah**a:** Československý spisovatel, **1988.**

- [ ] chybí autor kapitoly
- [ ] chybí název kapitoly
- [ ] Mezi názvem kapitoly a autorem knihy, ve které vyšla, by měla být předložka In:
- [ ] Čapkovi . --> prosím odstranit mezeru před tečkou
- [ ] Praha : --> prosím odstranit mezeru před dvojtečkou
- [ ] opět přesunutí roku vydání za nakladatele

**Populární romány Vlasty Javořické**. Mocná, Dagmar. Česká literatur**a. 1955,** ro**č. X**LIII, č. **5, s. 487-509**.

- [ ] chybí název článku
- [ ] Česká literatur**a.** --> odstranit mezeru před čárkou, změnit čárku za tečku
- [ ] Česká literatura. **1995,** Za název časopisu přesunout rok vydání (zakončit čárkou a mezerou za ní) 
- [ ] ro**č.X**LIII --> doplnit mezeru za tečku za "roč." ---> roč. XLIII
- [ ] Přidat čárku za číslo časopisu a pokračovat stranami, které teď chybí

Getta, Jelizaveta. **Styl v literárním překladu prizmatem Karla Hausenblase**. Bohemica litteraria. **2022,** ro**č. X**XV, č. 1, **s. 76-96**. DOI: 10.5817/BL2022-1-5.
- [ ] chybí název článku
- [ ] Bohemica litterari**a ,** --> odstranit mezeru před čárkou, změnit čárku za tečku
- [ ] Bohemica litteraria. **2022,** Za název časopisu přesunout rok vydání (zakončit čárkou a mezerou za ní) 
- [ ] ro**č. X**XV, --> doplnit mezeru za tečku za "roč."
- [ ] Přidat čárku za číslo časopisu a pokračovat stranami, které teď chybí

**Comment by albertoh** [comment]
Nektere reference nemaji prefix mods: . Musim s tim pocitat? To znamena zdvojovat kod...
Nebo to je chyba techto testovacich zaznamu, a bude vzdy spravne napsan xml s namespace mods: ?

**Comment by kerschfilip** [comment]
Je to chyba testovacích záznamu, vůbec jsem si to původně neuvědomil. Ten prefix mods: tam vždy bude.

**Comment by albertoh** [comment]
Opravim kod, az bude ten zaznam v poradku, OK?

**Comment by albertoh** [comment]
Jeste tam chybi type=personal pro name

**Comment by kerschfilip** [comment]
oboje by mělo být v testovacím záznamu opravené: https://kramerius-test.lib.cas.cz/uuid/uuid:6ed2135a-8844-4235-b5ec-8da5f200601c

**Comment by albertoh** [comment]
Je tam opravena verze

**Comment by kerschfilip** [comment]
@albertoh je to téměř dokonalé :-) Moc díky.

Prosím jen za názvem a před "In:" smazat mezeru před tečkou:

![image](https://github.com/user-attachments/assets/d859d9ce-fdad-4b2e-9def-63a582b140ec)

---

Zkoušel jsem přidat další citace (vytvořené přes ProArc) ke článku [Proměna kritické recepce](https://asjournals.inovatika.dev/ceskaliteraturaK7/article/uuid:6f2371fd-d53d-463c-ab93-429e7a7fb8a1/detail), ale nezobrazují se mi tam. Přestože se zdá, že zaindexované jsou. 
![image](https://github.com/user-attachments/assets/5b67e12d-6eb0-4883-98d8-baacfe1941dc)


Stejně tak se mi teď nezobrazují ani nestrukturované citace u https://asjournals.inovatika.dev/ceskaliteraturaK7/article/uuid:6ed2135a-8844-4235-b5ec-8da5f200601d/detail, kde to předtím určitě šlo

**Comment by kerschfilip** [comment]
Opravy OK, děkuju!

Mám poslední drobnost: v případě, že mám definovanou pouze počáteční stránku citovaného článku, tak se mi v citaci ukazuje např: _Pérez Berenguel José. La figura de Henry Swinburne y las características de su viaje por España. In: Cuadernos Dieciochistas. 2008, roč. 9, s. 211-_**undefined** Mohlo by to prostě místo "undefined" končit tou pomlčkou?

A potom tady u toho testovacího článku zase bojuju s tím, že se mi ze tří citací (viz [tady](https://asjournals.inovatika.dev/api//search/get_pid?pid=uuid:5ecce8b4-afd2-4136-89d1-3f6fac38f671&withParent=true)) ukazuje jen jedna: https://asjournals.inovatika.dev/ceskaliteraturaK7/article/uuid:5ecce8b4-afd2-4136-89d1-3f6fac38f671/detail. A přitom type=personal tam teď určitě mám :-)

**Comment by kerschfilip** [comment]
Na dnešní schůzce jsme se domluvili, že se upraví ještě zobrazení citace pro monografie podle toho, jak vytváří MODS ProArc:

ProArc vytvoří tuto strukturu:
```xml
<mods:relatedItem ID="ref0021" type="references">
      <mods:identifier type="isbn"> 978-84-96408-23-4</mods:identifier>
      <mods:name type="personal">
        <mods:namePart type="family">Ortas Durand</mods:namePart>
        <mods:namePart type="given">Esther</mods:namePart>
      </mods:name>
      <mods:relatedItem type="host">
        <mods:originInfo>
          <mods:dateIssued>2006</mods:dateIssued>
        </mods:originInfo>
        <mods:titleInfo otherType="volume">
          <mods:title> Leer el camino: Cervantes y El „Quijote“ en los viajeros extranjeros por España (1701–1846). Biblioteca de estudios cervantinos 18</mods:title>
        </mods:titleInfo>
      </mods:relatedItem>
    </mods:relatedItem>
```

ASJournals sestaví citaci: 
`Ortas Durand Esther. . In: Leer el camino: Cervantes y El „Quijote“ en los viajeros extranjeros por España (1701–1846). Biblioteca de estudios cervantinos 18. 2006. ISBN: 978-84-96408-23-4.`

Správně by měla citace vypadat takto:
`Ortas Durand Esther. Leer el camino: Cervantes y El „Quijote“ en los viajeros extranjeros por España (1701–1846). Biblioteca de estudios cervantinos 18. 2006. ISBN: 978-84-96408-23-4.`

Zároveň prosím pozor, aby to nenarušilo sestavování citací pro články, kde se `In` používá, ty jsou teď správně, např: 
`Amenedo Costa Mónica. Miguel de Cervantes en The Monthly Review. In: Archivum. 2017, roč. 67, s. 7-`

**Comment by albertoh** [comment]
> Mám poslední drobnost: v případě, že mám definovanou pouze počáteční stránku citovaného článku, tak se mi v citaci ukazuje např: Pérez Berenguel José. La figura de Henry Swinburne y las características de su viaje por España. In: Cuadernos Dieciochistas. 2008, roč. 9, s. 211-undefined Mohlo by to prostě místo "undefined" končit tou pomlčkou?

Kde to je?

**Comment by albertoh** [comment]
> Zároveň prosím pozor, aby to nenarušilo sestavování citací pro články, kde se In používá, ty jsou teď správně, např:

To poznam podle pritomnosti mods:part v tom relatedItem?

**Comment by albertoh** [comment]
Na testu jsem dal verzi, jak jsem to pochopil :)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
@albertoh promiň, ale teď se rozpadlo zobrazení pro citaci článku, kde chybí tečka a mezera před In:

teď:  
Amenedo Costa Mónica. Miguel de Cervantes en The Monthly ReviewIn: Archivum. 2017, roč. 67, s. 7-. 

Má být:  
Amenedo Costa Mónica. Miguel de Cervantes en The Monthly **Review. In:** Archivum. 2017, roč. 67, s. 7-.

**Comment by albertoh** [comment]
Promin, snad uz je to vsechno.

**Comment by kerschfilip** [comment]
Skvělý! Moc děkuju za trpělivost.
