### ISSUE TITLE
Indexace Googlem a Google Scholarem

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#126]
V současnosti nejsou články v asjournals v Google Scholar vůbec indexovány, aby byly indexovány je potřeba udělat změny na úrovni struktury webu, zpřístupnění bibliografických údajů jednotlivých článků pomocí `meta` tagů a umožnit přidávat k článkům soupisy použité literatury.

Informace k tomu, co je potřeba splnit vychází z [dokumentace Googlu](https://scholar.google.com/intl/en/scholar/inclusion.html#overview)

##  1) Struktura webu

- [x] webová stránka nesmí vyžadovat přihlášení, instalaci speciálního SW, zavírání vyskakovacích oken nebo klikání na odkazy/tlačítka či posouvání stránky dolů, aby bylo možné si přečíst celý abstrakt příspěvku nebo jeho plný text
- [x] webové stránky musí být strukturovány tak, aby automatické prohledávače mohli najít a načíst adresy URL všech článků
- [x] Články musí být ve formátu HTML nebo PDF. Soubory PDF musí mít prohledatelnou textovou vrstvu
- [x] URL každého článku musí být dostupná z domovské stránky pomocí maximálně deseti jednoduchých odkazů HTML
- [ ] použití Flash, JavaScriptu nebo navigace na základě formulářů ztěžuje automatizovanému systému nalezení článků. Tento typ navigace je potřeba doplnit o rozhraní pro „procházení podle data“, které používá pouze jednoduché odkazy GET HTML.
- [x] soubor robots.txt nesmí blokovat vyhledávací roboty Google v přístupu k článkům
- [ ] Naopak by měl blokovat roboty v přístupu k velkým dynamicky generovaným prostorům, které nejsou užitečné pro objevování článků.

## 2) Bibliografická data
Bibliografická data jednotlivých článků je potřeba zpřístupnit pomocí HTML tagů `<meta>`. Google Scholar podporuje značky Highwire Press:

- `citation_title` musí obsahovat název článku. Povinný tag.
- `citation_author` musí obsahovat autory. Nemá se používat pro autora webu nebo pro jiné přispěvatele než autory. Jména autorů mohou být uvedena buď jako „Smith, John“ nebo jako „John Smith“. Každé jméno autora musí být v samostatné značce, vynechány mají být všechny příslušnosti, tituly, certifikace atd. Alespoň jeden výskyt tagu je povinný.
- `citation_publication_date` musí obsahovat datum publikace. Uvést se má úplné datum „2010/5/12“, nebo samotný rok. Tento Tag je povinný
- `citation_journal_title` 
- `citation_issn` 
- `citation_volume` 
- `citation_issue` 
- `citation_firstpage` 
- `citation_lastpage` 

Všechny hodnoty tagů jsou atributy HTML, takže speciální znaky je nutné správně escapovat. Např. `<meta name="citation_title" content="&quot;Andar com meus sapatos" - uma an&#225;lise cr&#237;tica">`. U znaků, které jsou zapsány přímo v kódování znaků webové stránky, jako je latinská diakritika na stránce v ISO-8859-1, to není nutné. 

Značky `<meta>` se obvykle vztahují pouze na tu stránku, na které jsou uvedeny. Pokud tato stránka zobrazuje pouze abstrakt příspěvku a celý text je v samostatném souboru, např. ve formátu PDF, je třeba určit umístění všech plných textových verzí pomocí tagů `citation_pdf_url`. Obsahem tagu je absolutní URL souboru PDF. Dokumentace taky uvádí, že z bezpečnostních důvodů musí odkazovat na soubor ve stejném podadresáři jako abstrakt HTML (tady si nejsem jistý, jak to má být řešeno v našem případě)

**Tabulka meta:mods**:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-811d76e8-7fff-7e53-967e-81b15779037b"><div dir="ltr" style="margin-left:0pt;" align="left">

google scholar tag | úroveň objektu v DK | mods element | poznámka
-- | -- | -- | --
citation_title | model:article | titleInfo/title | vybrat titleInfo bez atributu “type”
citation_author | model:article | name | je potřeba spojit elementy namePart type="family"a type="given" dohromady
citation_publication_date | model:periodicalitem | originInfo/dateIssued | pokud bude vyplněn měsíc a rok (např. 05.2021), tak použít jen rok
citation_journal_title | model:periodical | titleInfo/title |  
citation_issn | model:periodical | identifier type="issn" případně type=”issn-l” | vzít issn-l, pokud není k dispozici a issn je víc, pak vzít poslední výskyt (stejné chováná jako web-client Krameria)
citation_volume | model:periodicalvolume | titleInfo/partNumber |  
citation_issue | model:periodicalitem | titleInfo/partNumber |  
citation_firstpage | model:article | part/extent/start |  
citation_lastpage | model:article | part/extent/end |  
citation_pdf_url |   |   | odkaz na stažení PDF

</div></b>
</body>
</html>

**Příklad pro jeden článek:**
```html
<!-- Příklad pro  https://kramerius.lib.cas.cz/uuid/uuid:53c5b0ca-39cd-4cd2-bfa2-c14701239d53 -->
<meta name="citation_title" content="Z Mikulova do Brna - neumannovská tiskárna a její produkce">
<meta name="citation_author" content="Jelínková, Andrea">
<meta name="citation_publication_date" content="2021">
<meta name="citation_journal_title" content="Knihy a dějiny">
<meta name="citation_volume" content="28">
<meta name="citation_issue" content="1-2">
<meta name="citation_firstpage" content="39">
<meta name="citation_lastpage" content="69">
<!-- Pro K5 -->
<meta name="citation_pdf_url" content="https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:53c5b0ca-39cd-4cd2-bfa2-c14701239d53/streams/IMG_FULL">
<!-- Pro K7 -->
<meta name="citation_pdf_url" content="https://kramerius.lib.cas.cz/search/api/client/v7.0/items/uuid:edad6489-5c6d-4450-a37b-b53bda3de6b4/image">
```

### 3) Reference
Samostatně se má označit část příspěvku, která obsahuje odkazy na jiná díla, standardním nadpisem, například „Odkazy“ nebo „Bibliografie“. Jednotlivé odkazy v této sekci by měly být očíslovány buď "1. - 2. - 3." nebo "[1] - [2] - [3]" v PDF nebo v seznamu `<ol>` v HTML. Text každé reference musí být formální bibliografická citace v běžně používaném formátu, bez volného komentáře.

Možnost přidat seznam literatury se řeší v: https://github.com/ceskaexpedice/K5Journals/issues/125

**Comment by albertoh** [comment]
Metadata jsou pridane pro clanky

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
je to OK, díky!

**Comment by kerschfilip** [comment]
@albertoh na inovatika.dev to funguje dobře, ale na našem interním testu ty citační značky chybí (i u nově založených a naindexovaných článků). Je potřeba něco konfigurovat?

**Comment by albertoh** [comment]
Nemelo by. 
Hlavne aby to bezelo pod nodejs a meli byste nove konfigurace solru
Posli screenshoty.

**Comment by kerschfilip** [comment]
A co bys k tomu potřeboval? Já jsem to kontroloval tak, že jsem si zobrazil zdrojový kód stránky na detailu článku na Inovatice a u nás. A ta část týkající se Google Scholar u nás prostě chybí:

![Image](https://github.com/user-attachments/assets/73303162-e02e-43eb-a55e-68ea02ca633f)

**Comment by kerschfilip** [comment]
Aha, OK, pomocí dev tools to vidím i u nás

![Image](https://github.com/user-attachments/assets/ea075780-0f53-4ba8-b30f-4f0963b56388)

**Comment by albertoh** [comment]
A to znamena, ze problem je v nodejs.
Aplikace nejdriv podava pomoci nodejs prerenderovanou podobu stranky (to co vidime pomoci "zobrazit zdrojovy kod"). Tam uz by mely byt meta tagy

Potom se spusti angular script, ktery celou stranku obnovi a ozivi

**Comment by kerschfilip** [comment]
Akorát teda teď nevím, co s tím. NodeJS jsme restartovali, ale stav se nezměnil. V dev tools to vidět je, v zobrazit zdrojovy kod ne. Je fakt, že to testujeme na serveru, který je přístupný jen z KNAV (může to v zobrazování tagů hrát roli?), takže to klidně můžeme dořešit až v produkci, jen mě to zarazilo, že se to u nás chová jinak než na dev

**Comment by albertoh** [comment]
Nahodou nepristupujete rovnou na tomcat? port 8080? nodejs standartne bezi pres port 4000

**Comment by mduda100871** [comment]
Ahoj,

myslím, že problém je výrazně větší a rozsáhlejší než to vypadalo/vypadá. Řekl bych, že ani u K5, kde to teď máme v ostrém provozu, to ve skutečnosti nikdy nechodilo správně.

Analýzou jsem teď zjistil, že kód aplikace má zřejmě natvrdo zadrátováno (Je to tak Alberto?), že API Krameria je dostupné na adrese `http://localhost:8080/` a přes to vlak nejede. A to u našeho nasazení samozřejmě není.

Když jsem debugoval log běžícího nodejs, tak ať je nastavení v `~/.k5journals/config.json` jaké chci, pořád se to snaží dotlouct na ten localhost s portem 8080.

Abych mu tedy nasimuloval dostupný port 8080 na localhostu, zprovoznil jsem dočasně lokální tunel/proxy, který poslouchá na portu 8080 a forwarduje to na skutečný port Tomcatu kde běží serverová část aplikace, v našem případě 9083.

To ho zdá se uspokojilo, nicméně se začala ukazovat jiná chybová hláška:

![Image](https://github.com/user-attachments/assets/87b27bac-67d7-46be-b163-c3a4cfc5f458)

Pro jistotu opakuji, že teď mluvím o naší stávající ostré instanci ASJournals proti naší ostré K5!

MD

**Comment by mduda100871** [comment]
> Nahodou nepristupujete rovnou na tomcat? port 8080? nodejs standartne bezi pres port 4000

Ne, forward proxy na frontendu komunikuje s aplikací na portu `4000`, kde poslouchá nodejs.

**Comment by mduda100871** [comment]
Takže na testovací K7 s novou verzí ASJournals to nicméně vypadá, že to chodí(?).

![Image](https://github.com/user-attachments/assets/1bec1c24-06fc-4dde-bb24-98d2bb360870)

i s tím, že nemá k dispozici ten localhost s portem 8080.

Když mu také nahodím lokální tunel, jako v předchozím případě, tak sype tuto hlášku:

![Image](https://github.com/user-attachments/assets/3b4c6022-b12f-4a79-859b-0f66a0987f35)

kde mě trochu znervózňuje ta okolnost, že tam operuje s http protokolem, kde ale dostane jen redirect (301) na https.

Takže zatím jsem tedy z toho chování aplikace hodně rozpačitý.

MD

**Comment by mduda100871** [comment]
Mimochodem, máme opravdu naprosto identickou verzi aplikace jako máte nasazenou ve firmě?

Já jen, že například zdrojové kódy zde na gitu podle všeho s oficiálně posledním distribučním balíčkem určitě nekorespondují - jak v tags, tak ani branches...

**Comment by kerschfilip** [comment]
@albertoh mohl by ses na tohle prosím podívat? Děkuju

**Comment by albertoh** [comment]
Ahoj.
Aplikace bezi pod tomcatem a nodejs.

S API krameria komunikuje backend, tj, java cast bezici pod tomcatem. Adresa Krameria se nastavuje v konfiguracnim souboru ~/.k5journals/config.json

nodejs komunikuje jen s java API aplikace. Pri spusteni service pro nodejs, je nutne pridat argument s adresou java API. Na wiki je priklad

https://github.com/ceskaexpedice/ASJournals/wiki/ASJournals

ExecStart=node server/main.js http://localhost:8080/ > node.log 2> node_err.log

Tam ale chybi vysvetleni. Prave http://localhost:8080/ je adresa aplikace v tomcatu z pohledu nodejs. Ve vasem pripade by melo byt:

ExecStart=node server/main.js http://localhost:9083/ > node.log 2> node_err.log

**Comment by mduda100871** [comment]
Ahoj,

je to celé složitější jak jsem psal. Nodejs běží ve vlastním/jiném kontejneru než samotný Tomcat. Tudíž nemá dostupný localhost/127.0.0.1 z bezpečnostních důvodů (by design).

I když mu předám vnější IP adresu jako parametr při startu, tak to nebere, jak jsem psal, a v logu neustále vidím, že se dobývá na 'http://localhost:8080'.

Celé jsem si to teď nasimuloval na naší testovací instanci. Kontejner s Nodejs jsem pustil přímo na síťovém stacku hosta (což ale není v produkci doporučeno), takže se dostane na localhost hosta.

Vnější port kontejneru s Tomcatem je nastaven (na testu) tentokrát na 9090, takže takto vypadá konfigurace v `config.json`:
```
{
    "client":{
    },
    "server":{
      "solr.host": "http://10.118.0.86:8983/solr/",
      "api.point.k7": "https://kramerius-new.lib.cas.cz/search/api/client/v7.0",
      "img.point": "https://kramerius-new.lib.cas.cz/search/img",
      "langsMap" : {
        "cs": "cze",
        "en": "eng",
        "de": "ger"
      },
      "citation_server": "http://citace.kramerius.cloud/v1/kramerius?format=html&url=https://kramerius.lib.cas.cz&uuid="
    }
}
```
A v `docker-compose.yml` se Nodejs staruje takto (opět zdůrazňuji, že je povolen síťový stack hosta, takže to bere localhost):
```
...
command: "node server/main.js http://127.0.0.1:9090/"
...
```
Proměnné prostředí uvnitř kontejneru pro Nodejs jsou nastavené na:
```
PORT=4000
HOST=0.0.0.0
```
Když zkusím obyčejný test hlaviček pomocí `curl`, tak Nodejs normálně funguje:
```
$ curl -I 'http://localhost:4000/'
...
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 544064
ETag: W/"84d40-cHO8+PsAkBSAHG2lq7u96Rqgk/c"
Date: Fri, 14 Feb 2025 19:36:45 GMT
Connection: keep-alive
Keep-Alive: timeout=5

...
```
Nicméně, jakmile zkusím nějakou validní stránku v prohlížeči, tak Nodejs začne trotlit a dobývat se na `http://localhost:8080` (naprosto nehledí na to, co mám v konfiguraci):

![Image](https://github.com/user-attachments/assets/6c2d43f1-d340-46ea-92f5-ef48616d58e1)

A tady jsem tedy nasimuloval dostupnost portu `8080` na `localhost` pomocí tunelu (proto jsem povolil kontejneru síťový stack hosta, jak jsem psal výše):
```
socat -dd tcp-l:8080,fork,reuseaddr tcp:127.0.0.1:9090
```
Jakmile tunel nahodím, tak se Nodejs uklidní. Z toho evidentně plyne, že někde v té naší aplikaci je natvrdo zadrátován ten `localhost` s portem `8080`. Můžeš mi to prosím potvrdit nebo vyvrátit?

Jsou někde k dispozici aktuální zdrojové kódy verze, kterou máme nasazenou?

A druhá zásadní otázka. Jak poznám, že se aplikace chová z hlediska indexace Googlem validně?

Je toto žádoucí stav (stav po nahození tunelu se simulací dostupnosti portu 8080 na localhostu):

![Image](https://github.com/user-attachments/assets/01bef81a-3150-4a65-84c1-2fa8c1304ad6)

nebo není? Pokud ne, jak tedy mám otestovat, že to funguje podle požadavku?

Díky, MD

P.S.: Pokud to tady nevyřešíme, budeme muset dát nějakou on-line schůzku s živou demonstrací....

**Comment by mduda100871** [comment]
Jo a ještě jedna chyba, kterou vypisuje Nodejs do logu, když má teď k dispozici ten localhost na portu 8080:

![Image](https://github.com/user-attachments/assets/2358ae06-b9d4-4554-acea-499c586dc25e)

kde na `http://asjournals-test.lib.cas.cz` je pouze redirect (301) na `https://asjournals-test.lib.cas.cz`.

Takže tipuji, že ta chyba je způsobena tím, že aplikace neprovede ten redirect a tudíž nějaký xml parser nedostane validní odpověď - pouze můj odhad.

MD

**Comment by albertoh** [comment]
Mas pravdu, uz vidim jedno misto....
Opraveno. Je nove release
https://github.com/ceskaexpedice/ASJournals/releases/tag/v4.0.2

**Comment by mduda100871** [comment]
Ahoj,

teď to vypadá výrazně lépe, rozhodně už se to nedobývá na ten localhost a bere na vědomí konfiguraci (v tomto případě je vidět jméno kontejneru):

![Image](https://github.com/user-attachments/assets/f5683f05-8faf-4162-a3a0-b067d7774e95)

žádné chyby na produkční instanci to při proklikáváni na konzoli nodejs neháže, takže za mě asi dobré.

Teď akorát, zda-li to opravdu dělá co má? Poznám to podle toho, co jsem se ptal výše u screenshotu konzole prohližeče? Jde o ty meta tagy?

Na testovací instanci nodejs háže na konzoli nějakou chybu, ale to připisuji asi nějakému problému v samotné konfiguraci toho časopisu? Má nás to zajímat?

Díky, MD

P.S.: Alberto, je možné k tomu binárnímu distribučnímu balíčku vygenerovat i aktuální balíčky zdrojového kódu?

**Comment by albertoh** [comment]
> P.S.: Alberto, je možné k tomu binárnímu distribučnímu balíčku vygenerovat i aktuální balíčky zdrojového kódu?

V tom release jsou dole, jako zip a tar

**Comment by albertoh** [comment]
Byl tam spatny branch.
Uz je to
https://github.com/ceskaexpedice/ASJournals/releases/tag/v4.0.3

**Comment by mduda100871** [comment]
Ahoj,

drobný postřeh k té chybě, která se objevuje na konzoli `nodejs` (výše viz screenshot).

Na testovací instanci se chyba objevuje a na budoucí ostré instanci (jinak obě identické, poslední release, obě nad K7)  nikoliv.

Vypozoroval jsem, že obě instance se trochu liší v chování v případě, kdy na hlavní stránce si vyberu nějakou instanci časopisu ze seznamu časopisů a kliknu na ní.

U ostré instance se konkrétní vybraný časopis zobrazí ve stejném tabu jako výchozí seznam a žádná chyba na konzoli `nodejs` nevypadne.

Naopak u testovací instance, pokud na výchozím seznamu vyberu nějakou konkrétní instanci časopisu, kliknu na ní, tak se otevře v novém tabu vedle a na konzoli `nodejs` vypadne chyba.

MD

**Comment by albertoh** [comment]
Ahoj.
Tu chybu jsem videl. Ale nemuzu najit zdroj, kde a jak se to stava.  Ten stack nedava zadnou uzitecnou informaci.
Na funkcnost stranky nema vliv.
Jeste budu zkoumat dal, ale je to divne

**Comment by albertoh** [comment]
Konecne jsem nasel problem. Jsem postupne vypinal radky, dokud to nezmizelo :) A potom fixnul
Je novy release

**Comment by mduda100871** [comment]
Tak nasazeno, chyba už se neukazuje, proklikával jsem ty jednotlivé časopisy opakovaně.

Snad je to všechno.

Díky, MD
