### ISSUE TITLE
Modernizace designu aplikace

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#127]
Modernizovat design aplikace tak, aby odpovídala současným trendům v designu. Bude potřeba udělat návrh a specifikaci a tu si odsouhlasit. 

Redesign by měl zahrnovat vyřešení barevných přechodů, které teď v některých barevných kombinacích nevypadají dobře, možná umožnit administrátorům vybrat si více než jednu barvu a kompletně podporovat mobilní zobrazení

**Comment by pkudela** [comment]
Ahoj @kerschfilip , chtel bych zjistit vice prodrobnosti tykajici se tohoto issue. Jedna se o to, o cem jsme pred casem bavili, cili kompletni redesign aplikace? Tim navrhem mas na mysli navrh zcela noveho layoutu aplikace v nejakem grafickem nastroji, napr. sketch, photoshop atd.? Kdo tento graficky navrh ma udelat, my, nebo nekdo od vas? Ptam se proto, ze vytvoreni takoveho grafickeho navrhu zabere docela hodne casu, pokud budu brat v potaz navrh vsech pohledu aplikace, jejich postupne schvaleni a pak naslednou implementaci. Nebo se jedna o redesign aplikace v podobnem duchu, jako jsem delal v ProArcu? Toto je potreba si ujasnit kvuli odhadu casove narocnosti.

**Comment by kerschfilip** [comment]
Ahoj @pkudela, jasně, tady je určitě potřeba to víc specifikovat. Bylo by možné, že bychom to třeba trochu probrali po schůzce k ProArcu 7.9.?

Layout aplikace by měl zůstat v zásadě stejný, jde nám spíš o to, aby to celé působilo trochu více seriózně a méně stísněně. Když se třeba podíváš na nějaký web používající OJS (https://openjournalsystems.com/portfolio/) nebo třeba na web [Teorie vědy](https://teorievedy.flu.cas.cz/index.php/tv), tak to sice není nijak zvlášť hezké a zajímavé, ale přeci jen to působí nějak lépe.

V rámci rozvoje by se tak jednalo vlastně o podobný rozsah redesignu jako u toho klienta ProArcu s tím, že největší problémy vidíme v:

- těžkopádnosti záhlaví a menu
- přílišné výraznosti footeru
- dopočítávání barevných odstínů z jedné barvy 
  - když se vybere blbá barva, tak ty dopočítané vypadají špatně a mohou způsobit nedostatečný kontrast mezi textem a pozadím
  - přechody mezi barvami nejsou konzistentní a působí (podle mě) trochu zvláštně, třeba tady jednou barva bledne do přechodu, jednou tmavne a jednou se nemění
  - řešení by mohlo být vybrat při zakládání webu paletu dvou nebo tří barev místo jedné a s těmi potom pracovat
![image](https://github.com/ceskaexpedice/K5Journals/assets/57805328/5b2084fa-1257-469e-846a-517f7c74d3fd)

Bylo by dobré si rámcově nějaký návrh schválit (třeba že řekneme, že menu bude vypadat podobně jako na nějakém webu apod.), ale nechceme dělat grafické návrhy s pohledy na různé obrazovky aplikace.

**Comment by pkudela** [comment]
Ahoj @kerschfilip, diky za odpoved, tohle uz je vice konkretni a dle toho kratkeho popisu v tom nevdim problem. Cili jestli to dobre chapu, tak layout / rozvrzeni stranky a jednotlivych prvku zustane stejne, ale jedna se spise o zmenu designu cele aplikace, aby to pusobilo sveze, jednoduse a ciste + nejak vyresit tu barevnost. Pri tom samozrejme budeme muset sahnout i do typu a verze frameworku, bootstrap bych zemenil za angular material nejnovejsi verze, ale to probereme na schuzce 7.9. jak si zminil.
