### ISSUE TITLE
Tlačítka v hlavním menu - dvojí funkčnost

### ISSUE THREAD

**Issue by AnnaNajmanova** [ceskaexpedice/ASJournals#130]
Redakce nás upozornily na  tlačítka v horním menu, které mají dvě funkce: při zmáčknutí se objeví jednak nový text, jednak se rozbalí roletka s nabídkou. Když se klikne jen na okraj tlačítka, rozbalí se pouze roletka. Tato dvojí funkčnost je pro uživatele podle zpětné vazby, kterou jsme dostali matoucí, uživatel může kvůli tomu přehlédnout důležité informace. 

Prosíme změnit tlačítka v horním menu tak, aby měla vždy jen jednu funkci - buď vedou pouze na text, nebo mají funkci roletky a text se po kliknutí na ně nebude měnit.

**Comment by albertoh** [comment]
Nove, pokud maji podmenu, jen se otevira tak, ze prvni polozka podmenu je ten hlavni link

**Comment by AnnaNajmanova** [comment]
Narazili jsme při testování na návrh k úpravě - v menu, šipka která značí rozbalovací roletku je na levé straně by měla být napravo :
![šipky v menu](https://github.com/ceskaexpedice/ASJournals/assets/89901869/976f98f5-8f70-4d91-89ec-891a7c1bdf96)

 + stejný problém je i u tlačítek řazení (Rubriky - Archiv, Vyhledat..)
![šipky u řazení](https://github.com/ceskaexpedice/ASJournals/assets/89901869/aa0355bd-491a-47cb-b4f3-d292dc87fdd6)

**Comment by albertoh** [comment]
Opraveno
