### ISSUE TITLE
Zpětná vazba při přidávání/odstraňování čísel

### ISSUE THREAD

**Issue by AnnaNajmanova** [ceskaexpedice/ASJournals#131]
V současné době, když se pohybujeme v administraci a přidáváme uuid, zobrazuje se kolečko, že proces probíhá. Stejně to funguje při mazání. Ne vždy ale zmizení kolečka označuje konec a úspěšnost přidání/mazání.

Administrátoři by ocenili, kdyby se na konec operace zobrazilo vyskakovací okno s textem ""chyba""/""Vše v pořádku"". Zkrátka hláškou, že je možné pokračovat a není potřeba čekat dál s další akcí.

Souvisí s #143

**Comment by AnnaNajmanova** [comment]
Zpětná vazba při odstraňování čísel není, při přidávání je, ale bylo by možné v češtině?
![Zpětná vazba](https://github.com/ceskaexpedice/ASJournals/assets/89901869/6cf5a1c9-6232-4f65-af3e-9a1c4ac58245)

**Comment by kerschfilip** [comment]
Otestováno, ještě k tomu máme pár výhrad:

- [ ] zpětná vazba je v angličtině (při přidání píše "totally indexed...", při odstranění "deleted X documents". Prosím předělat do češtiny, jestli to jde
- [ ] Okno pro potvrzení smazání nemá překlad nadpisu (teď je tam admin.confirm), prosím udělat ho stejně jako v ProArcu, tedy nadpis "Smazání objektů" nebo "Smazání UUID", to je jedno. `Ano` udělat červeně a dát ho doleva.
- [ ] Je jedno, jestli v okně pro potvrzení smazání uživatel vybere `Ne` nebo `Ano`, stejně se data smažou
<img width="723" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/de285c9b-8a98-44e1-8e7b-625612c2f21f">
<img width="412" alt="Snímek obrazovky 2024-04-10 v 13 26 07" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/f12613d2-c786-45c8-a227-a0a6492d84aa">

**Comment by albertoh** [comment]
Pridal jsem preklady

**Comment by kerschfilip** [comment]
Při indexaci se tam na konci toho českého textu ukazuje` Zpracováno:`, ale zatím žádné číslo. Předtím tam byl asi počet naindexovaných článků? 
![image](https://github.com/user-attachments/assets/ee22c568-88b3-40aa-9355-758090ac7d3b)

Smazání nevygeneruje žádnou hlášku, že se to povedlo,  ale text "indexace skončila". Prosím ještě o úpravu

![image](https://github.com/user-attachments/assets/cacd2dd6-b7b6-4b30-95a8-2b717980c461)

**Comment by albertoh** [comment]
Jake je to journal? K7?

**Comment by kerschfilip** [comment]
Tohle jsem zkoušel tady: https://asjournals.inovatika.dev/korpus/, je to K5.

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
Přidání UUID v pořádku, při smazání mi to ale pořád píše "Indexace skončila":
<img width="484" alt="image" src="https://github.com/user-attachments/assets/5eceddd7-57f7-4ecb-ac12-c6260f9a7efd">

**Comment by albertoh** [comment]
Hotovo

**Comment by kerschfilip** [comment]
Zpětná vazba OK, ještě by to chtělo překlad, to je asi na @pkudela v rámci #167 ? 
<img width="479" alt="image" src="https://github.com/user-attachments/assets/6683de09-13bc-4763-8540-6b2bce4027e8">

**Comment by pkudela** [comment]
> > Zpětná vazba OK, ještě by to chtělo překlad, to je asi na @pkudela v rámci #167 ? <img alt="image" width="479" src="https://private-user-images.githubusercontent.com/57805328/390368851-6683de09-13bc-4763-8540-6b2bce4027e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MDYzMTQsIm5iZiI6MTczMjcwNjAxNCwicGF0aCI6Ii81NzgwNTMyOC8zOTAzNjg4NTEtNjY4M2RlMDktMTNiYy00NzYzLTg1NDAtNmIyYmNlNDAyN2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDExMTMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMWQ0ZjdjYTY0Y2FlMjM4ZmI3MDU0OTgwZTYyZjk4ODhiYmZlYzBjMDYyYzIwNGZmNWQ1NTRhNDYzMGRiMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PPRr05yrPXJNKuckl0JS-WbO4tj-96HvM-BQTVBWWns">
> 
> Ano, chystam se na to uz dlouho, nedostava se casu, ale uz se to blizi :-), do konce tohoto tydne chci vsechny issue napsane na me dodelat.

Ahoj @kerschfilip ja v kodu ten preklad vidim, muzu pri testovani na asjournals.inovatika.dev neco mazat, pridavat atd.? Proste cokoliv?

**Comment by kerschfilip** [comment]
@pkudela jasně, na tom dev serveru si dělej co chceš :-) Hodně je toho třeba v časopisu [Cornova](https://asjournals.inovatika.dev/cornova/).

**Comment by pkudela** [comment]
hotovo, pokracuji uz v issue #167
