### ISSUE TITLE
Zalamování názvu/podnázvu

### ISSUE THREAD

**Issue by AnnaNajmanova** [ceskaexpedice/ASJournals#133]
Redakce často poukazují na problém dlouhého názvu/podnázvu - příliš dlouhý název/podnázev časopisu způsobuje v hlavičce webu ošklivé zalomení.
Řešením by bylo umístit podnázev časopisu na samostatný řádek pod název.

**Comment by pkudela** [comment]
Dobry den, toto by melo byt vyreseno s novym redesignem viz. screenshot, muzete pripadne vyzkouset zde na testovacim -> https://asjournals.inovatika.dev/knihyadejiny/home

<img width="489" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/ebd6927f-b25a-4e3c-9866-8b6ca980251d">
