### ISSUE TITLE
Přidat role pro osoby

### ISSUE THREAD

**Issue by AnnaNajmanova** [ceskaexpedice/ASJournals#134]
Jednotliví autoři mají v MODS uvedené role, aplikace ale tyto role ignoruje a všechny souhrně označuje jako autory (zkratka "aut").

Představa je, že u autorů by se měly zobrazovat jejich role, v levém panelu by se neměly zobrazovat jména autorů s rolí ""trl"" by se měly zobrazovat jen v detailu článku, ne v levém panelu a archivu.

**Comment by AnnaNajmanova** [comment]
Autoři se zobrazují ve výpisu článků, ale ne v detailech jednotlivých článků, není tedy možné otestovat zapojení rolí
![Autoři](https://github.com/ceskaexpedice/ASJournals/assets/89901869/7c72c7c4-ae69-40dc-bb2a-e691088d6270)

**Comment by AnnaNajmanova** [comment]
Aktuálně mají autoři a další role napsanou roli v závorce: 
![Autoři](https://github.com/ceskaexpedice/ASJournals/assets/89901869/4365a7b5-2408-46eb-bf84-6f033ebd6b0b)

Potřebujeme, aby role byla přímo napsána před dvojtečkou a pak jméno - Role: Jméno - bez závorek za jménem
Příklad: 
![Recenzent](https://github.com/ceskaexpedice/ASJournals/assets/89901869/37a5e428-494c-4fca-9b25-613ce9225e56)

**Comment by albertoh** [comment]
Tim padem, potrebuju vsechny mozne zkratky roli a jejich preklady

**Comment by kerschfilip** [comment]
@albertoh role by měly být stejné jako v ProArcu: [česká verze](https://github.com/proarc/proarc/blob/37ef4944f1056cea59fe2198258a3056a529b000/proarc-common/src/main/resources/cz/cas/lib/proarc/common/config/modsRoleTerms_cs.json#L36) a [anglická verze](https://github.com/proarc/proarc/blob/37ef4944f1056cea59fe2198258a3056a529b000/proarc-common/src/main/resources/cz/cas/lib/proarc/common/config/modsRoleTerms.json)

**Comment by albertoh** [comment]
Zkopirovano z Proarcu
