### ISSUE TITLE
Oblast časopisu

### ISSUE THREAD

**Issue by AnnaNajmanova** [ceskaexpedice/ASJournals#135]
V současnosti je možné zadat pouze jednu oblast, která časopis charakterizuje, ale narazili jsme i na časopisy, které měly problém pouze s jedním zařazením a požadovaly i například 3 oblasti. 

Představovali jsme si podobné pole a funkci jako je u klíčových slov. Tedy, že oblastí bude možné přidat více oblastí, pomocí tlačítka +, které by bylo stejné jako u Klíčových slov. 
+ Oblast by mělo být možné zadat pro anglickou a českou verzi vstupního portálu.

**Comment by albertoh** [comment]
Anglictina souvisi s #139

**Comment by kerschfilip** [comment]
Oblast v angličtině by měla být libovolný text vyplněný přes admin rozhraní, ne kontrolovaný slovník závislý na lokalizačním souboru. Díky!

**Comment by albertoh** [comment]
Kdyz jsme o tom diskutovali dohodli jsme se prave implementovat kontrolovany slovnik.
Jinak by to znamenalo plne menit hledani podle jazyku. Tj, pri zmene jazyka v rozhrani melo by se menit seznam poli pouzivanych pro facety, i logika filtrovani a hledani.
 Lze to delat, ale nebude to okamzite

**Comment by albertoh** [comment]
Pripraveno

**Comment by kerschfilip** [comment]
V administraci jde přidat více oblastí časopisu, nedaří se mi ale je odstranit - když kliknu na křížek, tak se nic neděje: 
![image](https://github.com/ceskaexpedice/ASJournals/assets/57805328/60e0ee6f-1603-460d-9e4b-1c8646c2ad16)
Celkově administrace nějak špatně odpovídá - tady mám třeba zakliknutou Cornovu, ale ve formuláři mi zůstává jiný časopis:
![image](https://github.com/ceskaexpedice/ASJournals/assets/57805328/c832746e-2e6a-42ad-a047-4563ad2047ca)

Po přepnutí do angličtiny mi potom oblasti zůstávají česky:
![image](https://github.com/ceskaexpedice/ASJournals/assets/57805328/93f516b0-49ab-42dc-80cf-3b1978a69de7)

**Comment by kerschfilip** [comment]
Tohle je nyní OK
