### ISSUE TITLE
Angličtina na rozcestníku

### ISSUE THREAD

**Issue by AnnaNajmanova** [ceskaexpedice/ASJournals#139]
Na úvodní stránce webu je možné přepnout zobrazení do angličtiny, ale nepřekládají se hodnoty u klíčových slov a oboru, ale také ani název.

Bylo by ideální doplnit tyto dvě fasety a název o anglické varianty.

**Comment by albertoh** [comment]
Hlavni nazev hotovo.
Co se tyce klicovych slov a oboru:
jak si to predstavujete, ze pridate seznam klicovych slov v anglictine, nebo maji se pridat do lokalizacniho jsonu preklady ?

**Comment by kerschfilip** [comment]
Název OK, díky. 

Klíčová slova i oblasti by v angličtině měly být nastavitelné přes administraci, nepřidával bych je do lokalizačního souboru

**Comment by kerschfilip** [comment]
Klíčová slova zatím nejsou rozlišena podle jazyků, mělo by to být udělané stejně jako u oblastí, tam už je to OK

**Comment by kerschfilip** [comment]
OK, díky!
