### ISSUE TITLE
Podtitulek (i titul?) v angličtině

### ISSUE THREAD

**Issue by AnnaNajmanova** [ceskaexpedice/ASJournals#140]
Při přepnutí webu do angličtiny se nepřekládá název a podnázev časopisu - od redakcí nám přišlo několik dotazů, zda by bylo možné zadat i název/podnázev v aj. 

Řešením by bylo umožnit vyplnit pole pro anglickou variantu názvu a podnázvu časopisu.

**Comment by albertoh** [comment]
![image](https://github.com/ceskaexpedice/ASJournals/assets/5946836/57ac8f8b-cc25-46ff-87ac-d93ff497bef9)

**Comment by kerschfilip** [comment]
Funguje, ale jak to prosím bude fungovat v případě, že si v návaznosti na https://github.com/ceskaexpedice/ASJournals/issues/141 vytvořím ještě 3. jazykovou mutaci? Třeba němčinu? Kam pak vyplním Německý titulek a podtitulek?

**Comment by kerschfilip** [comment]
Pole na vyplnění v administraci jsou, ale do nadpisu časopisu se jejich obsah nepřenese:
![image](https://github.com/ceskaexpedice/ASJournals/assets/57805328/ea9ca55b-2224-43ce-9e3c-10122d7ffce5)
![image](https://github.com/ceskaexpedice/ASJournals/assets/57805328/49c87cbb-d71f-4099-99c4-eac9845d2fc8)

**Comment by albertoh** [comment]
Ja to vidim. Napr:

![image](https://github.com/ceskaexpedice/ASJournals/assets/5946836/5f15cb58-e360-4990-97c3-8cc3eae59c40)

**Comment by kerschfilip** [comment]
@albertoh no ale v tom tvém případě bys tam měl přece vidět "**Le Acta Onomastique** Le Test", ale ten podnadpis tam chybí.

**Comment by albertoh** [comment]
Jo... Opraveno

**Comment by kerschfilip** [comment]
super, díky!
