### ISSUE TITLE
Redesign administrace

### ISSUE THREAD

**Issue by AnnaNajmanova** [ceskaexpedice/ASJournals#143]
Současný stav je pro administrátory lehce zmatený. 

Možností by bylo použít vzhled z administrace klienta proarcu. Rozdělit administraci na 3 sekce: Přidat uuid, Stránky, Konfigurace
Odstranit volbu Kramerius 7 z administrace časopisu, nechat ji pouze na úrovni konfigurace časopisu v administraci portálu.

Návrhy zde: https://drive.google.com/drive/folders/1IpTTC26yAdcDqL5g5Kz-AUcijTtjbyFh?usp=sharing

**Comment by albertoh** [comment]
Je to tam az na tohle:

![image](https://github.com/ceskaexpedice/ASJournals/assets/5946836/80bed65b-0c27-4973-88a6-59c254d5e776)

Nevim co tim myslite

**Comment by kerschfilip** [comment]
- [ ] ještě na záložce Konfigurace prosím do pole pro licenci doplnit placeholder. Např jen "název licence"

**Comment by albertoh** [comment]
> [ ] ještě na záložce Konfigurace prosím do pole pro licenci doplnit placeholder. Např jen "název licence"

Odstranil jsem to pole. Licence se nastavi v dialogu. Tam placeholder je

**Comment by kerschfilip** [comment]
Ještě mě napadlo (jestli mě nezabijete), že je super, jak se po nahrání obálky rovnou ukáže, co uživatel nahrál. Ale kdyby se mezi tlačítkem Nahr**á**t a tou obálkou dala udělat malá mezera, bylo by to úplně skvělý (-:
(a prosím opravit Nahrat na Nahrát)

<img width="513" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/d3e02b1e-3f66-4bc4-a9d3-348697ca2beb">

**Comment by pkudela** [comment]
hotovo

<img width="325" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/0b6730dc-ace4-4cac-91ef-a123e2ee9853">

**Comment by kerschfilip** [comment]
Díky!

Ale ještě mám další :(

- [ ] Místo tlačítka nahrát se teď objevuje button.upload:

![image](https://github.com/ceskaexpedice/ASJournals/assets/57805328/45513aa5-072b-448f-9065-63bce022ffcf)

- [ ] na kartě konfigurace by se měla po kliknutí na tlačítka `Uložit` apod vracet zpětná vazba, že k uložení došlo, obecně se to řeší v #131

**Comment by pkudela** [comment]
> Díky!
> 
> Ale ještě mám další :(
> 
> * [x]  Místo tlačítka nahrát se teď objevuje button.upload:
> 
> ![image](https://private-user-images.githubusercontent.com/57805328/328444480-45513aa5-072b-448f-9065-63bce022ffcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTUwNjIsIm5iZiI6MTcxNTA5NDc2MiwicGF0aCI6Ii81NzgwNTMyOC8zMjg0NDQ0ODAtNDU1MTNhYTUtMDcyYi00NDhmLTkwNjUtNjNiY2UwMjJmZmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE1MTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzN2VjNWMzMWJlYzI5MDViOTllOWQ5MWM3N2Y4Yzg1YjIyNDcyYTEyNGM1M2JlY2VjMWFmMDA2MjE0YTQ3OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d9NH5TCsZ0Nij51sgOuGRAYb503whbNQIzt7Nb6HUBY)
> 
> * [ ]  na kartě konfigurace by se měla po kliknutí na tlačítka `Uložit` apod vracet zpětná vazba, že k uložení došlo, obecně se to řeší v [Zpětná vazba při přidávání/odstraňování čísel #131](https://github.com/ceskaexpedice/ASJournals/issues/131)

to mas asi spatne v cache, zkus si dat tvrdy reload, pripadne vymazat cache prohlizece, me se to zobrazuje spravne jak na locale, tak i na serveru
cestina:
<img width="470" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/17d15dd9-f17f-462f-a815-dfecfbfbd49e">

anglictina
<img width="532" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/23bb21b1-a0c3-4b73-9a87-2ddfdd26139b">

**Comment by pkudela** [comment]
Doplnen snack bar pro vsechny akce. @albertoh u nastaveni licenci se otevre dialog a tlacitko ulozit nema zadnou metodu pro ulozeni zmen, vytvoril jsem ji a do ni vlozil service pro zobrazeni snackbaru, mrkni na to pak prosim a dopln potrebne do metody, dik.

**Comment by kerschfilip** [comment]
za mě je teď chování OK, je potřeba ještě něco dodělávat, jak píšeš výše @pkudela?

**Comment by albertoh** [comment]
Metoda je ve volajici komponente. Mozno zavrit
