### ISSUE TITLE
Špatný odkaz na vložené PDF

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#145]
Při vkládání PDF přes textový editor se vytvoří špatný odkaz. V HTML je to `<a href="/lf?action=GET_FILE&...`, správně má ale odkaz začínat **/api**, takže: `<a href="/api/lf?action=GET_FILE&`
<img width="656" alt="20230908_asjournlas_pdf1" src="https://github.com/ceskaexpedice/K5Journals/assets/57805328/a39c7145-69e6-412e-8d66-181a601429be">

**Comment by AnnaNajmanova** [comment]
Nejde vůbec vložit - ![Vložení](https://github.com/ceskaexpedice/ASJournals/assets/89901869/66733cbe-4fe1-49b2-a196-2e1690f700a4)

**Comment by kerschfilip** [comment]
Stále mi to nejde. Můžu už vybrat soubor k nahrání, ale když kliknu na `Nahrát`, tak se nic nestane, nahrané PDF nevidím a nemůžu ho vložit do textu:

<img width="851" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/d480ac1c-2af3-4d44-bd60-b75827e3ae9b">

**Comment by kerschfilip** [comment]
Funguje, díky
