### ISSUE TITLE
Ošetřit neexistující stránky

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#146]
Při přístupu na stránku, která není v rámci webu vytvořená (třeba `/eshop` místo `/e-shop`) zobrazit informaci o nenalezené straně (error 404). Nyní se zobrazuje "Text not found in..."

**Comment by kerschfilip** [comment]
Aktuálně to vypadá takto:
<img width="1226" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/e57ac8ea-a346-483a-b096-0b9177f31f4c">

Je prosím možné text "Page not found (error 404)" někde upravit, aby třeba měl českou a anglickou verzi?

**Comment by albertoh** [comment]
Lze. Ale to je varovani ne pro uzivatele, ale spise pro administratora casopisu, ktery by mel pridat ten text v administraci

**Comment by kerschfilip** [comment]
tohle považuji v současné době za dostatečné, takže issue zavírám
