### ISSUE TITLE
Vytvorit sidenavbar pro zobrazovani na mobilnich zarizenich

### ISSUE THREAD

**Issue by pkudela** [ceskaexpedice/ASJournals#148]
<img width="675" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/42b96b41-d059-4410-b9cc-8b1e6ecd4b2f">

**Comment by pkudela** [comment]
Pouziva se jedna komponenta pro mobilni zarizeni i pro desktop, takze to usnadni pripadne upravy.

**Comment by kerschfilip** [comment]
Super, díky!
