### ISSUE TITLE
Řazení časopisů na hlavním webu 

### ISSUE THREAD

**Issue by AnnaNajmanova** [ceskaexpedice/ASJournals#149]
Pokud se časopisy seřadí od Z-A, na konci stránky pod patičkou vznikne bílý prostor (při řazení od A-Z  je to v pořádku)
![Řazení časopisů](https://github.com/ceskaexpedice/ASJournals/assets/89901869/2b3ce5d2-19c3-4a4f-9602-f3979a133e42)

**Comment by AnnaNajmanova** [comment]
Když se nově založí časopis, nefunguje řazení od A-Z, ani od Z-A na vstupním portále. Nově založený časopis je buď na začátku nebo na konci, nezařadí se mezi ostatní, příklad _Knihy a dějiny 2_ založený za účelem testování.
![image](https://github.com/ceskaexpedice/ASJournals/assets/89901869/6ce533e0-eace-437a-ac30-a478152fb8cc)

**Comment by albertoh** [comment]
Opraveno

**Comment by AnnaNajmanova** [comment]
Funguje, díky

**Comment by kerschfilip** [comment]
@albertoh znovu otevírám, protože v angličtině se časopisy na hlavní stránce řadí nějak špatně podle abecedy:

![image](https://github.com/user-attachments/assets/1757d930-260e-4a79-b752-e8e419168d0a)

**Comment by albertoh** [comment]
Opraveno
