### ISSUE TITLE
Zarovnání webu

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#152]
V návaznosti na #127 je nyní webová stránka časopisu natažená na celou šířku obrazovky. Bylo by prosím možné ji malinko odsadit od okrajů, obdobně jako to bylo ve staré verzi?, ale možná ne tak dramaticky. (s tím že lišta menu by asi zůstala po celé délce?)

Dál prosím:

- [x] V rámci archivu zarovnat jednotlivé ročníky a čísla na střed
- [x] Na obrazovce po rozkliknutí ročníku (když jsou zobrazena [jednotlivá čísla](https://asjournals.inovatika.dev/cornova/archiv;pid=uuid:93cdea17-44e5-407a-940e-008ad3cbe8a2)), tak je také zarovnat na střed + slovo "číslo" napsat s velkým "Č"
- [x] Tlačítko TISK je v některých případech dost natěsno k textu, bylo by ho možné odsadit?
<img width="898" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/3a44488a-19e5-4b50-97eb-cd73d89aad12">

**Comment by pkudela** [comment]
@kerschfilip ahoj, par poznamek k tomu co si psal. Neni tomu tak, ze je obsah zobrazeny na celou sirku obrazovky, text je fixovany v containeru se standardni delkou 1280px, takze na vetsich obrazovkach je pres celou obrazovku pouze navbar, breadcrumb lista a paticka. Co se tyce zarovnani textu na stred, u predchozi aplikace to bylo jinak, bylo tam odsazeni z leva cemuz bych se rad vyhnul, potom tyto nestandardni upravy mohou nadelat par problemu. Pokud se Ti zda u nekterych stranek zbytecne roztahany, tak jsem pro tyto ucely nadefinoval jeste jeden container s delkou 960px. Tento container jsem aplikoval zatim ma stranku archivu, rocniky a stranku o casopisu, muzes se podivat, jestli by Ti to takto vyhovovalo, muzeme tento container klidne jeste zmensit, standardne jsou k dispozici hodnoty 1280px, 960px, 600px, 400px. Cili sel bych asi cestou bud vsude zmensit delku conaineru, coz by ale zase nekde bylo na skodu napr. u ctecky, nebo tento container nastavit jen u vybranych stranek. Nize posilam screenshoty pred a po uprave.

pred upravou conaineru
<img width="1502" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/f66ea767-65e7-4c72-abfb-05a95cab4d27">

po uprave
<img width="1507" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/b199687c-300c-40d5-b1c9-17ab6d86c741">

pred upravou conaineru
<img width="1512" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/e5d6521b-3eae-4ae8-9959-76b52526d867">

po uprave
<img width="1512" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/3cd14a26-47e7-4af3-9f69-90a722a3c98a">

pred upravou conaineru
<img width="1509" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/0195bbfe-352a-4bc6-b703-8049df2336f1">

po uprave
<img width="1512" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/a8ac3ea1-753b-4dba-9f65-830a06cb8615">

**Comment by pkudela** [comment]
prosim o otestovani, nasazeno na serveru

**Comment by kerschfilip** [comment]
Díky moc za vyzkoušení. 

Nakonec bych asi nechal všude těch 1280px a na 960px to omezil jen v archivu (archiv, rozkliknutý ročník i číslo) a na aktuálním čísle. Tam to jinak vypadá podle mě blbě, jak se to namačká na tu levou stranu.

Šlo by na těch 1280px zarovnat i header, navbar, breadcrumb lištu a patičku? Mně se nějak moc nelíbí, jak to jde až do kraje, přijde mi, že kdyby to šlo trochu odsadit, bylo by to lepší.

**Comment by kerschfilip** [comment]
Chápu, za nás je to takhle, jak je to teď na testu, OK. Děkuju.
