### ISSUE TITLE
Zabarvení aktuálně rozkliknutého ročníku v archivu

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#153]
Při rozkliknutí ročníku v archivu se mi v levém menu s vobou dalších ročníků vždy zvýrazňuje ten prostřední, ne ten, na kterém aktuálně stojím. Např [zde](https://asjournals.inovatika.dev/knihyadejiny/archiv;pid=uuid:f79ea345-ec31-4aac-8a41-9d048d31f02e), ve staré podobě to bylo [takto](https://asjournals.lib.cas.cz/knihyadejiny/archiv;pid=uuid:8ab01d02-6c1b-4997-ba02-eec8748656ed)
<img width="840" alt="Snímek obrazovky 2024-04-10 v 15 31 50" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/61116574-b7e0-482c-8114-c7bf4ee1e552">

**Comment by AnnaNajmanova** [comment]
Funguje, díky!
