### ISSUE TITLE
Změna fontu

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#154]
Po redesignu aplikace (#127) se teď používá na webu font Roboto. Na původním webu ale bylo Roboto-Condensed-Light. Poprosil bych o změnu, nebo nás ještě napadlo zkusit kombinaci podobnou, jako mají teď naši [knihovědci na svém webu](https://kvo.lib.cas.cz/). Na nadpisy používají Montserrat a na běžný text EB Garamond. Co si o tom myslíš, @pkudela ? Šlo by to vyzkoušet?

Zároveň jsme si všimli, že teď trochu zaniká ten nadpis Aktuálně na hlavní stránce. Šlo by ho, prosím, udělat barevně - tou barvou, kterou má web zvolenou za svou hlavní? 

Díky!

**Comment by pkudela** [comment]
@kerschfilip toto muze byt problem, respektive prvni varianta s puvodnim pismem Roboto-Condensed-Light vyzkousim, pak uvidime

**Comment by pkudela** [comment]
@kerschfilip jeste dotaz, to pismo ma byt spolecne pro magazines a journals?

**Comment by pkudela** [comment]
@kerschfilip hral jsem si trochu s fonty, musel jsem nastudovat jak menit typography v materialu, tak jak to mame delane to neni uplne jednoduche to prebit, ale jsem blizko, vyzkousel jsem obe varianty, zatim bez nejakych hlubsich uprav, mam na mysli velikosti pisma atd: 

**Fonty, jako maji na knihovnickem webu**
<img width="1512" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/1af25ead-3364-4c01-bc82-218a36aa097c">

<img width="1512" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/390848fe-a736-4e48-8aa1-73a86ca6fb60">

Font co byl v predchozi verzi
<img width="1512" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/c051e9bd-fe51-44ea-9a8a-1c802492ffab">

<img width="1512" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/41c01296-c002-4768-8bbb-ef1daa6d9755">

Dej vedet, co ti je blizsi.

**Comment by pkudela** [comment]
zmeneno

**Comment by kerschfilip** [comment]
Aktuální varianta je OK, díky. Jen nám to písmo přijde docela malé. Bylo by možné ho z aktuálních 14px změnit na 16px? A adekvátně i nadpis, který je použitý např. pro "Aktuálně" na hlavní stránce zvětšit a udělat tučnější, aby vystupoval?

**Comment by pkudela** [comment]
@kerschfilip ano, je to mozne, zkusim si s tim pohrat

**Comment by pkudela** [comment]
Zvetseni pisma v body na 16px, v zavislosti na teto zmene jsem zvetsil h1 z 24px na 26px a h2 z 20px na 22px, co se tyce ostylivaneho "aktualne" apod. tak tam jsem jeste zmenil font-weight ze 200 na 400

prikladam puvodni
<img width="1509" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/ea34dc22-da62-42af-9158-d6b748eb4150">

a toto je nove, co bude na testu
<img width="1512" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/68d3097f-f909-4d14-a34e-e3abb284f661">

**Comment by pkudela** [comment]
nasazeno, prosim o otestovani

**Comment by pkudela** [comment]
@kerschfilip jeste jsem u body textu zmenil vlastnost line-height, aby byl text lepe citelny

**Comment by kerschfilip** [comment]
@pkudela je to mnohem lepší, díky! 

Ještě jsme tu ale diskutovali o tom, že ta písmena jsou dost smrsknutá k sobě (to je divný, když se font jmenuje Roboto-Condensed-Light, že jo) - je složité to ještě přehodit celé na jiný? Hrál jsem si s tím v prohlížeči a přišlo nám, že to vypadá líp, když se použíje např. [Inter ](https://fonts.google.com/specimen/Inter)(patří taky do google fontů)

**Comment by pkudela** [comment]
@kerschfilip uplne si nejsem jisty, jestli je to lepsi, porovnej

 **Inter**
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/590ae18d-0212-481b-9ddd-2b51d757987c">

**Roboto Condensed**
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/d9aa293c-f7d4-43f7-ab0e-d446d0c9f20d">

**Inter**
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/39224e6f-ef98-4019-8874-cc180a40bc2f">
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/f797c9fa-e0e8-4db9-90cc-8533f231afd0">

**Roboto Condensed**
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/add7c447-4f4a-4e91-bdd0-4872eb1be0a6">
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/7dfe294f-2a5a-4e00-9e13-828c364ba92d">

**Comment by kerschfilip** [comment]
@pkudela taky si nejsme jistí. Prosím, nasaď Inter k testování a když to nebude dobrý, tak použijeme to Roboto s upravenými rozestupy. Děkuju!

**Comment by pkudela** [comment]
font zmenen a nasazeno

**Comment by kerschfilip** [comment]
Tak jsme to probrali a poprosím nechat Inter, ale změnit velikost na 14px a lineheight na 1,7. Hlavně na té úvodní stránce je to písmo hrozně velké, název časopisu na kartě je nalepený na Vydavatele, tak prosím případně upravit ty rozestupy. A písmo zmenšit i ve fasetách po pravé straně. To už bude úplně všechno :-)

**Comment by pkudela** [comment]
> Tak jsme to probrali a poprosím nechat Inter, ale změnit velikost na 14px a lineheight na 1,7. Hlavně na té úvodní stránce je to písmo hrozně velké, název časopisu na kartě je nalepený na Vydavatele, tak prosím případně upravit ty rozestupy. A písmo zmenšit i ve fasetách po pravé straně. To už bude úplně všechno :-)

Ahoj, velikost pisma jsem zmenil na 14px, co se tyce line-height, tak tam je ted nastaveno 24px, coz odpovida 1.7em, co si asi chtel, takze jsem to nechal jak to je, az si to proklias, tak prosim kdyz tak posli konkretni url nejakeho konkretniho pohledu se screeshoty, kde bys chtel pripadne neco jeste zmenit. Pokud to bude ok, tak prosim o zavreni.

**Comment by pkudela** [comment]
Take zbuildovano a nasazeno k testovani.

**Comment by kerschfilip** [comment]
Za ně už OK. Moc děkuju!
