### ISSUE TITLE
Problémy ve vyhledávání

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#155]
Při testování nové verze jsme narazili na problémy při používání obrazovky Vyhledat:

- [x] Nelze zvolit, kde se má zadaný text vyhledávat (v roletce vždy zůstane vybrané "kdekoliv")
- [x] Stejně tak zůstává vždy vybrané "a zároveň", nelze vybrat "nebo"
- [x] Vyhledávání nelze spustit klávesou Enter
- [x] listování mezi výsledky je v angličtině, i když je web přepnutí do češtiny:
<img width="1336" alt="Snímek obrazovky 2024-04-10 v 12 18 07" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/01da5040-bb9e-42d5-9509-e8cffc3501a9">

- [ ] A v rámci aktualizace designu nám přišlo lepší jednotlivá tlačítka označovat slovy s velkými písmeny (podobně jako je to ve vyhledávání na [knihovny.cz](https://www.knihovny.cz/Search/Advanced). Takže prosím udělat vždy první písmeno slova velké:
<img width="1496" alt="Snímek obrazovky 2024-04-10 v 12 12 57" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/ef664f37-f7eb-421e-9066-f51fe9294d15">

**Comment by AnnaNajmanova** [comment]
Ještě jsme narazili na problém u pole pro vyhledávání - pokud chci zrušit, objeví se hláška zrušit filtr (to je ok) ale místo kurzoru vyskočí tohle:

![image](https://github.com/ceskaexpedice/ASJournals/assets/89901869/b5154a51-d84c-44c0-8dc6-6389aee2bb58)

Ale zrušit to jde, spíše nám jde o to, aby uživatelé nebyli zmatení...

**Comment by pkudela** [comment]
@kerschfilip ahoj, nedokazi to nasimulovat, me se kurzor zobrazuje spravne

<img width="1494" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/7a185e33-f84b-46a5-a2e9-5bd8f5b42b2a">

**Comment by pkudela** [comment]
@kerschfilip uz to vidim, je to pokud neni zadany zadny dotaz, tak je tlacitko pro zruseni filtru disablovane, proto se kurzor objevuje takto, to je dle meho spravne, ze uzivatel vidi, ze je button neaktivni, ale muzu to zrusit

**Comment by kerschfilip** [comment]
Já mám teda teď taky problém nasimulovat to, co se s tím kursorem dělo předtím, ale obecně se to teď chová tak, že ten křížek pro zrušení filtru je šedý, pokud je pole s kritériem prázdné. Teprve když do něj něco napíšu, tak se zabarví. Funguje ale v obou případech.

Podle mě by měl být křížek zabarvený (aktivní) i když je pole prázdné. Můžu si třeba omylem udělat těch kritérií víc a pak je chtít odmazat, abych tam neměl zbytečně prázdné řádky:
![image](https://github.com/ceskaexpedice/ASJournals/assets/57805328/c1f1b203-76e5-4d46-aba8-ebdc8676ed08)

**Comment by kerschfilip** [comment]
super, děkuju!
