### ISSUE TITLE
Mobilní zobrazení pro vstupní portál

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#156]
Sidenavbar (https://github.com/ceskaexpedice/ASJournals/issues/148) funguje dobře na webech jednotlivých časopisů, ale na vstupním portále je skrytý příliš vpravo a uživatel ho tak nemusí najít:
<img width="260" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/f4a19e77-c2c2-482d-b19d-81c2f9324c0e">

Jako první se také uživateli zobrazují fasety - bylo by možné to změnit a fasety skrýt podobně, jako je to ve web-clientovi Krameria? Aby uživatel viděl rovnou nabídku časopisů a fasety si mohl zobrazit jen pokud chce?

<img width="254" alt="Snímek obrazovky 2024-04-10 v 15 58 08" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/915cd181-61a8-41b8-adf4-b8a9d685b2ac">

A když už jsme u těch faset - poprosil bych o změnu jejich řazení, aby to bylo stejné jako na současné produkční verzi: https://asjournals.lib.cas.cz/magazines/casopisy

**Comment by pkudela** [comment]
@kerschfilip co se tyce toho ovladaciho tlacitka na sidenav, tak to je chyba, nemelo by vubec dojit k horizontalnimu srollovani kvuli delce textu nadpisu, ted jsem to testoval, to opravim, k tomu mam dotaz:

- ma se text nadpisu casopisu zalamovat a s tim se bude zvetsovat vyska toolbaru viz. screenshot nize?
- nebo text bude postupne mizet s tremi teckami a vyska toobaru zustane stejna?

<img width="446" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/5c5165d7-311b-4850-9514-cb5d25f9dae9">

co se tyce tech facetu, jako je to v krameriovi, tam jsem uz to mobilni chovani takto koncipoval dopredu, tady to budu muset dodelat, pokud to chces, ale pujde to

**Comment by kerschfilip** [comment]
@pkudela ať se text nadpisu klidně zalamuje, i když to zvětší výšku toolbaru. Přijde mi to lepší, než kus textu neukazovat. 

K těm fasetám nevím, jak moc složité je to předělat. Jen teď prostě není ideální, že uživatel musí hrozně dlouho scrollovat než dojde na ty karty časopisů. Kdyby tě napadlo něco jiného jak to vyřešit, tak klidně. Mě napadlo jen to řešení v Krameriovi...

**Comment by pkudela** [comment]
> @pkudela ať se text nadpisu klidně zalamuje, i když to zvětší výšku toolbaru. Přijde mi to lepší, než kus textu neukazovat.
> 
> K těm fasetám nevím, jak moc složité je to předělat. Jen teď prostě není ideální, že uživatel musí hrozně dlouho scrollovat než dojde na ty karty časopisů. Kdyby tě napadlo něco jiného jak to vyřešit, tak klidně. Mě napadlo jen to řešení v Krameriovi...

NIc jineho a lepsiho nez jsem tenkrat vymyslel v klientovi krameria zatim neni :-) respektive, jine lepsi reseni me nenapada, uplne jednoduche to neni, ale slozite take ne, takze to udelam.

**Comment by pkudela** [comment]
hotovo, pri breakpointu mensim nez 959px se zobrazi lista s moznosti prepnout na filtry a nazpatek na vysledky, nasazeno, prosim o otestovani

<img width="573" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/31bac6a1-8c03-4685-bdd3-7f5688ff1f24">

<img width="567" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/3fb8d6f9-3b9e-4a42-9d26-77947af345fe">

**Comment by AnnaNajmanova** [comment]
U fazet bychom ještě chtěli poprosit o změnu jejich řazení, aby to bylo stejné jako na současné produkční verzi: https://asjournals.lib.cas.cz/magazines/casopisy

**Comment by albertoh** [comment]
Facety zmenene

**Comment by kerschfilip** [comment]
Super, moc díky!
