### ISSUE TITLE
Obsah čísla - redesign

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#157]
V rámci redesignu (#127) došlo k úpravám v [zobrazení obsahu čísla/ročníku](https://asjournals.inovatika.dev/knihyadejiny/archiv;pid=uuid:da939093-6b23-4269-ac32-dc2a29fef9ad). Stejný způsob vypisování jednotlivých článků se ale používá i v menu vedle prohlížečky nebo při vyhledávání.

Poprosili bychom o drobné úpravy:
- [x] Vytvořit mezi jednotlivými články větší rozestupy pro přehlednější odlišení
- [x] text "Recenzovaný článek" nedělat tučně, ale podbarvit ho šedou barvou (stejnou jaká je použita pro lištu s breadcrumbs) 
- [x] Počet zobrazení ani čísla stran nedělat tučně
- [x] u rozsahu stran zobrazovat pouze "s.", ne "s.:" a zobrazovat to pouze, pokud je rozsah k dispozici, jinak nezobrazovat ani "s."
<img width="967" alt="Snímek obrazovky 2024-04-10 v 12 55 28" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/b6025727-6490-471b-9261-83f11a5580b1">

- [x] vytvořit mezi textem "Počet zobrazení" a počtem zobrazení pevnou mezeru, aby nedocházelo k takovému zalomení:
<img width="332" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/9621d46d-ef73-49a8-94c6-307fd732b211">

**Comment by pkudela** [comment]
> V rámci redesignu (#127) došlo k úpravám v [zobrazení obsahu čísla/ročníku](https://asjournals.inovatika.dev/knihyadejiny/archiv;pid=uuid:da939093-6b23-4269-ac32-dc2a29fef9ad). Stejný způsob vypisování jednotlivých článků se ale používá i v menu vedle prohlížečky nebo při vyhledávání.
> 
> Poprosili bychom o drobné úpravy:
> 
> * [ ]  Vytvořit mezi jednotlivými články větší rozestupy pro přehlednější odlišení
> * [ ]  text "Recenzovaný článek" nedělat tučně, ale podbarvit ho šedou barvou (stejnou jaká je použita pro lištu s breadcrumbs)
> * [ ]  Počet zobrazení ani čísla stran nedělat tučně
> * [ ]  u rozsahu stran zobrazovat pouze "s.", ne "s.:" a zobrazovat to pouze, pokud je rozsah k dispozici, jinak nezobrazovat ani "s."
> 
> <img alt="Snímek obrazovky 2024-04-10 v 12 55 28" width="967" src="https://private-user-images.githubusercontent.com/57805328/321270573-b6025727-6490-471b-9261-83f11a5580b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjMyODksIm5iZiI6MTcxMjgyMjk4OSwicGF0aCI6Ii81NzgwNTMyOC8zMjEyNzA1NzMtYjYwMjU3MjctNjQ5MC00NzFiLTkyNjEtODNmMTFhNTU4MGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MTdjYmYxNjBhOTU3MzU5ZTBiYTIyZmE3MzE4ZjNlNzM0MDY2YTFlYTNkNmFkMjYxYTllYjI1ZWYwNzY5ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RGAmrdVwFuCEyxn05_1PqVMGDRAorh_2zurWj4qJfuE">
> * [ ]  vytvořit mezi textem "Počet zobrazení" a počtem zobrazení pevnou mezeru, aby nedocházelo k takovému zalomení:
> 
> <img alt="image" width="332" src="https://private-user-images.githubusercontent.com/57805328/321269960-9621d46d-ef73-49a8-94c6-307fd732b211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjMyODksIm5iZiI6MTcxMjgyMjk4OSwicGF0aCI6Ii81NzgwNTMyOC8zMjEyNjk5NjAtOTYyMWQ0NmQtZWY3My00OWE4LTk0YzYtMzA3ZmQ3MzJiMjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2Y2M1MjIxMTJlMjkyNjE4NTlmYjViMzYzYTExMWVjNTM5Mzk5NDRlMjQ1NTBhMzU1ZmRmNGVlYzVkYzU2MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9RZ0dYyuh9Zz1cZAZ_-gj-YFjoojKheATJVlEcI1sUk">

Procetl jsem ty body a asi v nicem nebude problem, udelam.

**Comment by pkudela** [comment]
prosim o otestovani, nasazeno na serveru

**Comment by AnnaNajmanova** [comment]
Ještě jsme narazili na drobnost u karty Aktuální číslo - články jsou dost nahuštěné na sebe, bylo by možné je od sebe odsadit stejně jako u Obsahu čísla?
![image](https://github.com/ceskaexpedice/ASJournals/assets/89901869/4d0d0935-908a-494f-bec6-4f64cb3a99f7)

**Comment by pkudela** [comment]
@AnnaNajmanova toto je bug, puvodne to odsazene bylo, ale zmenila se struktura komponent a tim padem se neaplikovala trida zajistujici odsazeni, toto by melo byt opravene.

<img width="524" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/ddc14fee-beb5-4bf9-a966-4aa89c1b894c">
<img width="1049" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/16591052/d5f38374-e622-4216-b57d-ae81e5be0baa">

**Comment by kerschfilip** [comment]
Super, díky.

Prosím už jen smazat mezery okolo pomlček u rozsahu stran. Tzn. například místo současného   
`s. 8 - 35`   
by to mělo být 
`s. 8-35`  

 Díky :-)

**Comment by pkudela** [comment]
> Super, díky.
> 
> Prosím už jen smazat mezery okolo pomlček u rozsahu stran. Tzn. například místo současného `s. 8 - 35` by to mělo být `s. 8-35`
> 
> Díky :-)

ok, udelam

**Comment by kerschfilip** [comment]
OK, díky!
