### ISSUE TITLE
Nepřekládání názvů stránek v menu při přepnutí jazyka

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#161]
Při přepnutí do angličtiny se názvy jednotlivých stránek v administračním menu nepřeloží do angličtiny, ačkoliv jejich anglický název je vyplněný:
<img width="981" alt="Snímek obrazovky 2024-04-10 v 16 35 28" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/4c56e9e5-ad7f-40dd-8b16-c34c77e1e21f">

Pokud by měl web v návaznosti na funkci z https://github.com/ceskaexpedice/ASJournals/issues/141 třetí jazykovou mutaci, kam by se vyplňoval název stránek? Vlastně je to podobný problém jako ve https://github.com/ceskaexpedice/ASJournals/issues/140

**Comment by albertoh** [comment]
Tam zobrazujeme ne nazbvy stran ale klic v URL, ktery musi byt unikatni. Nazev nemusi

**Comment by kerschfilip** [comment]
Aha, OK. Tak v tom případě zavírám. Díky
