### ISSUE TITLE
Nepotřebný nadpis na úvodní stránce časopisu

### ISSUE THREAD

**Issue by AnnaNajmanova** [ceskaexpedice/ASJournals#165]
Na úvodní stránce časopisu, nad textem, který se vkládá do "Hlavní stránka" je slovo Journal ... - bylo by možné odstranit?
(Pokud redakce budou chtít nadpis, vloží si ho do textu "Hlavní stránka" - vznikala by duplicita)

![image](https://github.com/ceskaexpedice/ASJournals/assets/89901869/c1f10719-b9ea-4c37-99c9-83e815c2453d)

**Comment by kerschfilip** [comment]
už je OK, díky
