### ISSUE TITLE
Obálka na stránce "Aktuální číslo"

### ISSUE THREAD

**Issue by AnnaNajmanova** [ceskaexpedice/ASJournals#166]
Na hlavní stránce je to obálka správně:
![image](https://github.com/ceskaexpedice/ASJournals/assets/89901869/e39c9a5a-80cb-4b6a-8e3a-2558235b27bc)

 ale na stránce "Aktuální číslo" je jiná:
![image](https://github.com/ceskaexpedice/ASJournals/assets/89901869/6315d97f-557b-48a1-9af8-b1b7cbcbe252)

Měla by být stejná, tedy ta první

**Comment by kerschfilip** [comment]
už je OK, díky
