### ISSUE TITLE
Archiv - doplnit drobečkovou navigaci

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#170]
Prosím doplnit drobečkovou navigaci při procházení archivu tak, aby se zobrazovalo i ve kterém ročníku a čísle je uživatel aktuálně přítomný.

Například zde by se mělo ukazovat:  
`Hlavní stránka / Archiv / 2021, ročník 62 / číslo 2`
<img width="872" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/ef3c46c1-0430-4d79-b63c-5a1d48aa0f96">

**Comment by pkudela** [comment]
@albertoh to je asi na tebe.

**Comment by albertoh** [comment]
Pridano

**Comment by kerschfilip** [comment]
@albertoh vypadá to dobře, díky!

Jak jsme to procházeli, tak nám z toho vzešly ještě tří věci na drobnou úpravu. Koukneš na to, prosím?

- [ ] někdy se v navigaci ukazuje rok i číslo ročníku časopisu, někdy ale jen rok. Vždy by to měl být rok i číslo ročníku.
takhle je to tedy správně: 
<img width="439" alt="image" src="https://github.com/user-attachments/assets/8808000f-c6cf-4521-b149-504faafb7e20">

takhle ne: 
<img width="361" alt="image" src="https://github.com/user-attachments/assets/ec96d7f8-dfdd-402c-aa31-69f52176b01f">

- [ ] Bylo by možné, udělat ročník i číslo jako odkaz, stejně jako [tady](https://asjournals.inovatika.dev/knihyadejiny/archiv;pid=uuid:da939093-6b23-4269-ac32-dc2a29fef9ad) je odkaz slovo Archiv?

- [ ] prosím upravit chování ještě na úrovní jednotlivého článku. Asi by bylo nejlepší tu část, co tam teď je vlastně přesunout do té drobečkové navigace:

![image](https://github.com/user-attachments/assets/9d2e337a-09fb-42d5-99be-005468be1b8f)

Takže by to bylo `Hlavní stránka/Archiv/ročník/číslo`

**Comment by albertoh** [comment]
> Bylo by možné, udělat ročník i číslo jako odkaz, stejně jako [tady](https://asjournals.inovatika.dev/knihyadejiny/archiv;pid=uuid:da939093-6b23-4269-ac32-dc2a29fef9ad) je odkaz slovo Archiv?

Nezda se, ale je to docela komplikovane

Ostatni jsem upravil. Snad jak jste chteli. Prosim o testovani

**Comment by kerschfilip** [comment]
Moc děkuju! 

Na ten hypertext jsem založil nové issue na nějaký budoucí rozvoj: https://github.com/ceskaexpedice/ASJournals/issues/181

Mohl bys ještě jen doplnit na úrovni článku `Archiv`? Nějak tam v rámci té cesty vypadl
<img width="383" alt="Snímek obrazovky 2024-11-26 v 15 33 14" src="https://github.com/user-attachments/assets/41035440-beb4-49f5-af14-27bdcbd8b309">

**Comment by albertoh** [comment]
Hotovo

**Comment by kerschfilip** [comment]
@albertoh nějak se mi teď vůbec nenačítá Archiv - třeba tady: https://asjournals.inovatika.dev/Knihy_a_dejiny/archiv

**Comment by albertoh** [comment]
Opraveno.
Bylo to zpusobeno tim, ze casopis jeste byl prazdny.

**Comment by kerschfilip** [comment]
Díky, už je to OK :-)
