### ISSUE TITLE
Archiv - zobrazovat všechny ročníky a čísla místo nejnovějších třech

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#171]
V Archivu při pohledu na čísla ročníků a články v číslu se po pravé straně nyní zobrazují 3 další (nejnovější) ročníky nebo čísla.

To může implikovat, že další ročníky nebo čísla neexitují - tzn. zobrazovat by se po levé straně měly všechny dostupné ročníky nebo čísla

<img width="859" alt="Snímek obrazovky 2024-05-28 v 15 07 45" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/815e7c99-b62d-41c1-9d43-05c27ee0c4ec">

Úplně si teda nejsem jistý, jak by to třeba v případě časopisu Acta Onomastica vypadalo, protože tam to budou desítky ročníků - ke zvážení je, jestli tam umožnit scrollovat jako mezi články v prohlížečce, nebo zobrazit jen tolik ročníků, kolik se na obrazovku vejde (prostě aby tam nebylo prázdné místo) - zajímal by mě váš názor @pkudela @albertoh co si myslíte, že bude uživatelsky přívětivější

**Comment by pkudela** [comment]
@albertoh asi na tebe

**Comment by albertoh** [comment]
Zkusim zobrazit vsechny, a reknete jak se to vam zda

**Comment by kerschfilip** [comment]
@albertoh je tohle k testu? Stále se mi tam ukazují jen 3 ročníky. Díky!

**Comment by albertoh** [comment]
Nebylo nasazeno. Ted uz je tam

**Comment by kerschfilip** [comment]
Myslím, že je to OK, díky

**Comment by kerschfilip** [comment]
jedna designová drobnost: [tady](https://asjournals.inovatika.dev/Knihy_a_dejiny/archiv;pid=uuid:a206065a-8503-4385-ba79-234d9e99c326?lang=cs) se kvůli dlouhým popiskům ročníku hrozně mačkají karty čísel (resp. čísla, u KaD je vždy jen jedno). Šlo by, prosím nastavit pro ten pravý sloupec nějakou max šířku (třeba 50 %), na které se to bude zalamovat, aby karty čísel nebyly v takových případech tak utlačované?

A potom když kliknu v levém sloupci na stejné stránce např. na "Rok 2012 číslo Zvláštní číslo PhDr. Anežce Baďurové", tak by bylo fajn, aby mi obrazovka zascrollovala zpět nahoru. To nevím, na kterého z vás je @albertoh @pkudela 

Děkuju

**Comment by kerschfilip** [comment]
![image](https://github.com/user-attachments/assets/6b18183c-4c18-4773-9121-d36238d02215)

**Comment by pkudela** [comment]
zmeneno na 50%, nasazeno, otestuj a dej vedet, @albertoh jeste dela na tom srollovano

**Comment by kerschfilip** [comment]
teď tam v archivu není nic vidět, tak snad je to tím, že @albertoh tam něco dělá :-)

![obrazek](https://github.com/user-attachments/assets/3af0e82f-1825-4ff9-bb97-13488134569f)

**Comment by kerschfilip** [comment]
Scroll OK, šířka taky. Děkuju!
