### ISSUE TITLE
Archiv / Ročník - doplnit řazení

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#172]
Aktuálně je možné řadit si od nejnovějších/nejstarších přehled ročníků v archivu, prosím doplnit tuto funkci i do jednotlivých ročníků (tzn. na obrazovku, kde jsou zobrazena čísla daného ročníku - https://asjournals.lib.cas.cz/ceskaliteratura/archiv;pid=uuid:da985ef6-b803-4dd7-b694-da76aa965506)

**Comment by albertoh** [comment]
@pkudela pridej mi tlacitko spravne. Ten flex disajn nechapu :)

**Comment by pkudela** [comment]
> @pkudela pridej mi tlacitko spravne. Ten flex disajn nechapu :)

Nevadi :-), je to tam, tak jen dodelej prosim funkcionalitu

<img width="1254" alt="image" src="https://github.com/user-attachments/assets/dd4586c0-5f2b-45c6-ac9c-a1dc5ffcfef5">

**Comment by kerschfilip** [comment]
Je to OK, jen prosím neumožňovat řazení na úrovni čísla, kdy už jsou vidět články. Tam to nedává smysl. Dík! https://asjournals.inovatika.dev/actaonomastica/archiv;pid=uuid:9dc8f3ed-494b-4bec-816b-7bd2a0734614

**Comment by pkudela** [comment]
> Je to OK, jen prosím neumožňovat řazení na úrovni čísla, kdy už jsou vidět články. Tam to nedává smysl. Dík! https://asjournals.inovatika.dev/actaonomastica/archiv;pid=uuid:9dc8f3ed-494b-4bec-816b-7bd2a0734614

ano, to Alebrto osetri podminkou, az bude delat funkcionalitu

**Comment by pkudela** [comment]
> > Je to OK, jen prosím neumožňovat řazení na úrovni čísla, kdy už jsou vidět články. Tam to nedává smysl. Dík! https://asjournals.inovatika.dev/actaonomastica/archiv;pid=uuid:9dc8f3ed-494b-4bec-816b-7bd2a0734614
> 
> ano, to Alebrto osetri podminkou, az bude delat funkcionalitu

Podminku jsem doplnil, az nasadim tak u clanku uz se zobrazovat nebude.

**Comment by pkudela** [comment]
Tak toto je cele hotove, radi to, me se zdalo, ze ne, ale to byl omyl, takze az @kerschfilip otestuje a bude ok, prosim zavrit.

**Comment by kerschfilip** [comment]
Za mě OK, díky!
