### ISSUE TITLE
Archiv - karty pro ročníky a čísla

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#175]
Orientaci v archivu by pomohlo, pokud by jednotlivé ročníky a čísla nesplývali tolik s pozadím, ale spíše z něj vystupovali. Bylo by možné jednotlivé ročníky a čísla v archivu zobrazovat jako karty (s bílým pozadím a jednoduchým stínem) podobně, jako jsou na vstupní stránce platformy prezentovány jednotlivé časopisy? 

Při najetí na kartu by se měl text "Rok XXXX, ročník XX" podtrhnout, aby bylo zřejmé, že se na to má klikat :-) 

Nepříliš povedená vizualizace:
<img width="539" alt="image" src="https://github.com/ceskaexpedice/ASJournals/assets/57805328/d8c7c751-03e3-4639-860e-8c6bddc6c5c2">

**Comment by pkudela** [comment]
@kerschfilip udelal jsem nasledovne

- archivni item jsem upravil tak, aby byl vizual jako karta
- po najeti mysi na kartu se karta podbarvi a zobrazi se kurzor pointer, tim padem je klikatelna cela karta, jak na urovni archivu, tak na urovni cisla
- po uprave archivni item, jsem musel upravit rozestupy nekterych elementu

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/7be35c64-f0d4-45c7-a7b0-e6463e51b4eb">

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/253ab3c6-940a-47da-874f-9fb26b780615">

**Comment by kerschfilip** [comment]
@pkudela je to super, moc díky! Šlo by ještě zkusit zarovnat text na kartě víc do středu? 

<img width="580" alt="image" src="https://github.com/user-attachments/assets/715dad4d-b6db-484d-a3f1-ccb41c90d59f">

**Comment by pkudela** [comment]
hotovo, aplikovano vertikalni centrovani na flex

**Comment by kerschfilip** [comment]
Super, díky!
