### ISSUE TITLE
Zobrazovat licenci článku z MODS

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#177]
V případě, že MODS článku obsahuje informaci o licenci v elementu `<mods:accessCondition>`, pak prosím na detailu článku zobrazovat obsah tohoto elementu. V případě, že element obsahuje atribut `xlink:href`, pak z hodnoty elementu udělat hypertextový odkaz.

Pokud `<mods:accessCondition>` součástí článku není, pak zobrazovat licenci nastavenou pro časopis tak, jak je to teď.

**Comment by kerschfilip** [comment]
Pokud by to šlo, prosím udělat místo https://github.com/ceskaexpedice/ASJournals/issues/137

**Comment by albertoh** [comment]
Muzes, prosim, mi ukazat nejaky priklad clanku, ktery to ma?

**Comment by kerschfilip** [comment]
Zatím pouze u nás na testu K7: https://kramerius-test.lib.cas.cz/uuid/uuid:b7e36f89-11b1-41ca-89af-3c2f38b146b4

**Comment by albertoh** [comment]
Tam se nedostavam. Chce po mne prihlasovaci udaje.

**Comment by albertoh** [comment]
On je uz zaindexovan u nas :)
https://asjournals.inovatika.dev/ceskaliteraturaK7/article/uuid:b7e36f89-11b1-41ca-89af-3c2f38b146b4

**Comment by kerschfilip** [comment]
Skvělý! 

prosím ještě:

- [ ] přejmenovat `Přístup k článku:` na `Licece`
- [ ] V případě, že se ukazuje obsah `<mods:accessCondition>`, tak schovat licenci nastavenou v rámci webu
(pokud ale nebude accessCondition v metadatech článku, tak normálně licenci nastavenou v rámci webu ukazovat) 

Tedy:
![image](https://github.com/user-attachments/assets/08baca7a-cf2e-4b5a-bc17-2eebc5e674d8)

**Comment by albertoh** [comment]
Hotovo

**Comment by kerschfilip** [comment]
Super, děkuju!
