### ISSUE TITLE
Citace se neaktualizuje podle vybraného článku

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#179]
Při překliknutí na jiný článek v levém menu se neaktualizuje vygenerovaná citace - zůstane stejná pro první článek, který si čtenář zobrazil:
![image](https://github.com/user-attachments/assets/0b891112-d665-4e45-95ea-0bf23afe65ad)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
Citace se teď aktualizují podle vybraného článku, ale negenerují. U naší testovací K7 je to asi v pořádku tím, jak není volně přístupná, ale nefunguje to ani u časopisů namířených na ostrou K5, např: https://asjournals.inovatika.dev/cornova/article/uuid:147ad32c-633b-4e30-863e-cd74ed793c69/detail

Myslím, že v rámci parametru url je navíc to `/uuid/`
![image](https://github.com/user-attachments/assets/3a618cad-e2fb-4ebb-ab96-ea5e322d6b35)

**Comment by albertoh** [comment]
Jo parametr uuid je navic. Mate ho v konfiguraci 
![image](https://github.com/user-attachments/assets/660b2c51-a2c0-4fe6-8f90-1bce20f453dc)

Kdyz ho odstranim uz funguje

**Comment by kerschfilip** [comment]
Aha, my to tak máme i na produkčním severu s tím uuid v konfiguraci, ani nevím proč, prostě to tak bylo u prvního časopisu, který se zakládal, tak to tak děláme dál.
![image](https://github.com/user-attachments/assets/0c79bed8-7512-453e-b6a1-af71bb6f7355)

Když to smažu, tak citace fakt funguje, tak snad se nerozbije něco jiného :-)
