### ISSUE TITLE
Mizející levý panel

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#180]
Pří přístupu přímo na článek nebo z [vyhledávání](https://asjournals.inovatika.dev/ceskaliteraturaK7/hledat/cokoliv;criteria=%5B%7B%22field%22:%22autor%22,%22fieldLabel%22:%22kdekoliv%22,%22value%22:%22Alaimo,%20Stacy%22,%22operator%22:%22AND%22,%22operatorLabel%22:%22a%20z%C3%A1rove%C5%88%22%7D%5D;start=0) se mi stává, že se nenačte levý panel s články v čísle: 

![image](https://github.com/user-attachments/assets/4cacc87f-234d-4343-9bfb-fb9257cb4533)

**Comment by albertoh** [comment]
Opraveno

**Comment by AnnaNajmanova** [comment]
Za mě vyřešeno, @kerschfilip za tebe ok?

**Comment by kerschfilip** [comment]
super, děkuju!
