### ISSUE TITLE
Prohlížečka - volba zobrazení v rámci konfigurace časopisu

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#182]
Otevírám ještě issue v návaznosti na https://github.com/ceskaexpedice/ASJournals/issues/124, kde jsme v zadání měli tohle:

> Navrhujeme rozdělit hlavní část obrazovky současné "prohlížečky" na dvě části: "detail" a "PDF". **Která z nich se bude defaultně zobrazovat bude nastavitelné v administraci časopisu**

Ta část o tom, která z těch částí je defaultně zobrazená v administraci chybí - bylo by možné to tam ještě dodělat?
V podstatě by šlo o to dodělat do administrace časopisu na kartu konfigurace ještě jeden přepínač: Prohlížečka: zobrazit detail/PDF

![image](https://github.com/user-attachments/assets/99972bbe-6ac2-4720-9367-df87a7af0a97)

Díky :-)

**Comment by albertoh** [comment]
Je to tam

**Comment by kerschfilip** [comment]
Super, díky!
