### ISSUE TITLE
Nesprávné zobrazení rozsahu let v dateIssued na kartě ročníků

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/ASJournals#183]
V archivu se na kartě ročníků s datem vydání v rozmezí několika let nezobrazuje žádná hodnota. Např. tady: https://asjournals.inovatika.dev/knihyadejiny_K7test/archiv

U problematických ročníků je dateIssued zapsáno např. takto
```xml
<mods:dateIssued>2009-2010 (2011)</mods:dateIssued>
```

V archivu se zobrazí pouze číslo ročníku, rozmezí let chybí:
![image](https://github.com/user-attachments/assets/bb72ac04-6f9a-4073-98ed-ba0294c7345d)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
OK, děkuju!
